### ISSUE TITLE
Default value of input

### ISSUE THREAD

**Issue by SaitDev** [graphql-java/graphql-java#1280] opened 2018-10-18 05:40 UTC
Having default value for input
```
input Default {
value1: Int = 0
}
```

send query to get schema
```
__schema {
    types {
      inputFields {
        defaultValue
      }
    }
  }
```

got error: 
```
{
      "message": "Expected type 'Int' but was 'IntValue'.",
      "path": "__schema.types.inputFields.defaultValue"
}
```

using version: 2018-10-17T09-47-16-c9ea5fc

**Comment by bbakerman** [comment] 2018-10-18 08:00
I just wrote a quick unit test on this issue but could not reproduce

```
package graphql

import groovy.json.JsonOutput
import spock.lang.Specification

class Issue1280 extends Specification {

    def "reproduce 1280"() {
        def spec = '''
            input Default {
                value1: Int = 0
            }
            
            type Query {
                field(arg : Default) : String
            }
        '''

        def graphQL = TestUtil.graphQL(spec).build()

        when:
        def executionResult = graphQL.execute('''
            {
            __schema {
                types {
                  kind
                  name
                  inputFields {
                    name
                    defaultValue
                  }
                }
              }
            }
            ''')
        then:
        executionResult.errors.isEmpty()
        println JsonOutput.prettyPrint(JsonOutput.toJson(executionResult.data))
    }
}

```

this has no errors and the data is as follows

```
{
    "__schema": {
        "types": [
            {
                "kind": "ENUM",
                "name": "__TypeKind",
                "inputFields": null
            },
            {
                "kind": "OBJECT",
                "name": "__Field",
                "inputFields": null
            },
            {
                "kind": "OBJECT",
                "name": "Query",
                "inputFields": null
            },
            {
                "kind": "OBJECT",
                "name": "__Schema",
                "inputFields": null
            },
            {
                "kind": "OBJECT",
                "name": "__Type",
                "inputFields": null
            },
            {
                "kind": "OBJECT",
                "name": "__EnumValue",
                "inputFields": null
            },
            {
                "kind": "ENUM",
                "name": "__DirectiveLocation",
                "inputFields": null
            },
            {
                "kind": "SCALAR",
                "name": "String",
                "inputFields": null
            },
            {
                "kind": "INPUT_OBJECT",
                "name": "Default",
                "inputFields": [
                    {
                        "name": "value1",
                        "defaultValue": "0"
                    }
                ]
            },
            {
                "kind": "SCALAR",
                "name": "Int",
                "inputFields": null
            },
            {
                "kind": "OBJECT",
                "name": "__InputValue",
                "inputFields": null
            },
            {
                "kind": "SCALAR",
                "name": "Boolean",
                "inputFields": null
            },
            {
                "kind": "OBJECT",
                "name": "__Directive",
                "inputFields": null
            }
        ]
    }
}
```

So it would appear to be working at first glance.  Can you outline more reproduction steps please

The message "Expected type 'Int' but was 'IntValue'." comes mostly like the from the GraphqlInt scalar  for the record which would seem to indicate the Introspection code getting things wrong on default values.

But this seems to be working based on my unit test

**Comment by bbakerman** [comment] 2018-10-29 04:03
I am going to close this for now.  If you find more reproduction steps please re-open it

**Closed by bbakerman** 2018-10-29 04:03 UTC
