### ISSUE TITLE
arguments in Directive introspection get extra double quotes

### ISSUE THREAD

**Issue by pvgoddijn** [graphql-java/graphql-java#2657] opened 2021-12-29 14:51 UTC
When you do a introspection query for the applied directives and a directive has a String as argument that argument will be wrapped in an extra set of double quotes

This is caused by the line: 
` return AstPrinter.printAst(literal);` on line 203 of `IntrospectionWithDirectivesSupport`

**To Reproduce**

```
       @Test
	public void testArgumentsDoubleQuoted() {
		GraphQLSchema schema = GraphQLSchema.newSchema()
				.query(GraphQLObjectType.newObject()
						.name("test")
						.withDirective(GraphQLDirective.newDirective()
								.name("direct")
								.argument(GraphQLArgument.newArgument()
										.name("arg")
										.type(Scalars.GraphQLString)
										.valueProgrammatic("valuewithouthquotes")
										.build())
								.build())
						.field(GraphQLFieldDefinition.newFieldDefinition()
								.name("texttest")
								.type(Scalars.GraphQLString)

								.build()))
						.build();
		IntrospectionWithDirectivesSupport directivesSupport = new IntrospectionWithDirectivesSupport();
		schema = directivesSupport.apply(schema);
		GraphQL build = GraphQL.newGraphQL(schema).build();
		ExecutionResult execute = build.execute("{\n" +
												" __schema {\n" +
												"  types {\n" +
												"    name" +
												"    appliedDirectives {\n" +
												"      name\n" +
												"      args {\n" +
												"        name\n" +
												"        value\n" +
												"      }\n" +
												"    }\n" +
												"  }\n" +
												" }\n" +
												"}\n");
		System.out.println(execute);
		Assertions.assertThat(execute.toString()).doesNotContain("\"valuewithouthquotes\"");
	}
```

**Comment by bbakerman** [comment] 2021-12-31 04:01
This is deliberate (but I will grant you seems strange if you have only string values)

The reason is this - we NEED to be able to describe what "value type" the applied directive `value` is

```
     type _DirectiveArgument {                    
          name: String!
          value: String!
     }
```

We chose to encode the values into a string?  Why - well because a directive value can be ANY valid graphql value (maps / list / ints / booleans / strings etc...)

But we cant know up front what the type is since its custom and a introspection consumer cant know either easily.

So the introspection value of an applied directive is an "AST printed" string.  Think of it like printed json (as an analogy)

So a boolean value is `"true"`, an integer might be `"42"` and a object type might be `"{ a : "b", c : 42 }"` (eg the AST printed version of a boolean / integer or object type.)

This means that a string value of `abc` becomes `""abc""` - yes that feels funny (when its just a string value) but its the canonical AST printed value of an graphql object.

The alternative would have been to just inside a "JSON" like blob of data in place and have no graphql type to describe it.  We choose not to do that.

Its a string value that canonically contains an AST printed value.  Hence a consumer can "canonically" decode it.

**Comment by bbakerman** [comment] 2021-12-31 04:01
I am closing this as not a bug.  Its strange for just string values but its not a bug - it's deliberate

**Closed by bbakerman** 2021-12-31 04:01 UTC

**Comment by pvgoddijn** [comment] 2021-12-31 15:05
just curious why this is deliberate? (why are other string arguments returned as a string and this as a quoted string? )

I end up with introspection that looks like this:
```
"inputFields": [
            {
              "name": "role",
              "appliedDirectives": [
                {
                  "name": "MyDirective",
                  "args": [
                    {
                      "name": "argumentValue",
                      "value": "\"the text value\""
                    }
                  ]
                }
              ]
            }
``` (using graphql-servlet)

This seems inconsistent?

**Comment by pvgoddijn** [comment] 2021-12-31 15:08
Thanks for the explanation
