### ISSUE TITLE
SchemaGenerator does not support @deprecated directive

### ISSUE THREAD

**Issue by tklovett** [graphql-java/graphql-java#502] opened 2017-06-15 16:37 UTC
It is possible to include a `foo: Foo @deprecated(reason: "this is why it's deprecated")` directive on a field within a schema IDL. However the `isDeprecated` and `deprecationReasons` are null at runtime.

If my understanding is correct, within `SchemaGenerator#buildField(BuildContext, TypeDefinition, FieldDefiniton)` there should be be some usage of `FieldDefinition.getDirectives()` to determine if `GraphQLFieldDefinition.Builder#deprecated(String)` needs to be called.

More broadly, `SchemaGenerator` doesn't seem to support directives at all.

**Comment by bbakerman** [comment] 2017-06-18 00:03
Thanks for reporting this problem.

A complete PR https://github.com/graphql-java/graphql-java/pull/470 is in place to add this as well as Ast support etc..

**Comment by bbakerman** [comment] 2017-06-18 00:13
Closing as duplicate of https://github.com/graphql-java/graphql-java/issues/468

**Closed by bbakerman** 2017-06-18 00:13 UTC
