### ISSUE TITLE
NPE thrown with malformed query

### ISSUE THREAD

**Issue by yspotts** [graphql-java/graphql-java#594] opened 2017-08-02 16:04 UTC
I am using published version 3.0.0. If I send a malformed query (e.g. missing a closing brace), GraphQL throws an NPE. 

The stacktrace points to  `graphql.GraphQL` line 204. The exception that is thrown has no root cause, and thus throws the NPE. 

This is the exception that is thrown:
`org.antlr.v4.runtime.misc.ParseCancellationException: There are more tokens in the query that have not been consumed`

**Comment by bbakerman** [comment] 2017-08-02 22:05
Can you please send a reproduction query so we can look at it in more detail.

Pretty sure that missing as trailing } has a unit test hence the need for a more specific query

**Comment by yspotts** [comment] 2017-08-02 22:15
sure. Here is a simple one that causes the issue:

```
{
      summary 
       }
      
}
```
It has a missing open brace

**Comment by bbakerman** [comment] 2017-08-07 23:11
Ok I have run this on master (4.x) and I do get an exception.  I do get an error but it does not blow up.

What version of graphql are you on?

The error could be improved for this.  Its currently

```
{
  "errors": [
    {
      "sourceLocations": []
    }
  ],
}
```

which is rubbish since it lost the error message. 

See #606 for that fix.

**Comment by bbakerman** [comment] 2017-08-07 23:12
I am going to close this issue because it currently does not NPE on master (4.x)

**Closed by bbakerman** 2017-08-07 23:12 UTC

**Comment by yspotts** [comment] 2017-08-07 23:19
Running version 3.0.0
