### ISSUE TITLE
GraphQLError is missing support for path field 

### ISSUE THREAD

**Issue by tklovett** [graphql-java/graphql-java#505] opened 2017-06-15 19:43 UTC
Today, `GraphQLError` only supports the required `message` field, optional `locations` field, and optional additional custom field(s). It is missing the `path` field, which is required when applicable.

From the GraphQL spec: https://facebook.github.io/graphql/#sec-Errors

> If an error can be associated to a particular field in the GraphQL result, it must contain an entry with the key `path` that details the path of the response field which experienced the error. This allows clients to identify whether a `null` result is intentional or caused by a runtime error.
> 
> This field should be a list of path segments starting at the root of the response and ending with the field associated with the error. Path segments that represent fields should be strings, and path segments that represent list indices should be 0‐indexed integers. If the error happens in an aliased field, the path to the error should use the aliased name, since it represents a path in the response, not in the query.
>...
> The response might look like:
> ```json
> {
>   "errors": [
>     {
>       "message": "Name for character with ID 1002 could not be fetched.",
>       "locations": [ { "line": 6, "column": 7 } ],
>       "path": [ "hero", "heroFriends", 1, "name" ]
>     }
>   ],
>   "data": {
>     "hero": {
>       "name": "R2-D2",
>       "heroFriends": [
>         {
>           "id": "1000",
>           "name": "Luke Skywalker"
>         },
>         {
>           "id": "1002",
>           "name": null
>         },
>         {
>           "id": "1003",
>           "name": "Leia Organa"
>         }
>       ]
>     }
>   }
> }
> ```
> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. In that case, the path for the error should include the full path to the result field where the error occurred, even if that field is not present in the response.

**Comment by bbakerman** [comment] 2017-06-15 22:46
Yes this is correct.  There is a PR in the works for this : https://github.com/graphql-java/graphql-java/pull/499

Thanks for reporting

I am closing this as a duplicate of #498

**Closed by bbakerman** 2017-06-15 22:46 UTC

**Comment by tklovett** [comment] 2017-06-15 22:55
Awesome! Thanks
