### ISSUE TITLE
Provide support in grammar for NULL value

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#432] opened 2017-05-12 22:23 UTC
The reference implementation has support for knowing that a value has deliberately been set to null or is absent.

https://github.com/facebook/graphql/pull/83

We could extend the grammar to allow a NullValue to be captured in syntax eg:

    field (arg : null)

The trick then would be how best to tell DataFetchers that the value is null literal versus not present

**Comment by andimarek** [comment] 2017-05-13 05:46
This is a duplicate of #427

**Closed** 2017-05-13 06:01 UTC
