### ISSUE TITLE
Getting ClassCastException when I use same schema for query and mutation both

### ISSUE THREAD

**Issue by Priyank780** [graphql-java/graphql-java#376] opened 2017-04-15 02:09 UTC
I'm trying to build schema which having structure,

```
Student{
ExtraInfo otherdetails;
}

ExtraInfo{
String key;
String detail;
}
```

Here is my graphql schema builder code,
```

GraphQLInputObjectType otherDetailsInputObjectType = GraphQLInputObjectType.newInputObject()
	.name("otherdetails")
	.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("key").build())
	.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("detail").build()).build();

GraphQLObjectType otherDetailsObjectType = GraphQLObjectType.newObject()
	.name("otherdetails")
	.field(newFieldDefinition().type(GraphQLString).name("key").build())
	.field(newFieldDefinition().type(GraphQLString).name("detail").build())
	.build();

GraphQLObjectType studentObjectType = GraphQLObjectType.newObject()
	.name("student")
	.field(newFieldDefinition().name("otherdetails").type(otherDetailsObjectType).build())
	.build();
	
GraphQLFieldDefinition studentFieldDef = newFieldDefinition()
	.name("student")
	.type(studentObjectType)
	.dataFetcher(new StudentDataFetcher())
	.argument(GraphQLArgument.newArgument().name("otherdetails").type(otherDetailsInputObjectType).build())
	.build();

GraphQLSchema schema = GraphQLSchema.newSchema()
	.query(GraphQLObjectType.newObject().name("query").field(studentFieldDef).build())
	.mutation(GraphQLObjectType.newObject().name("mutation").field(studentFieldDef).build())
	.build();

```

I'm getting below error,

Exception in thread "main" java.lang.ClassCastException: graphql.schema.GraphQLObjectType cannot be cast to graphql.schema.GraphQLInputType
	at graphql.schema.GraphQLArgument.replaceTypeReferences(GraphQLArgument.java:30)
	at graphql.schema.SchemaUtil.resolveTypeReferencesForFieldsContainer(SchemaUtil.java:153)
	at graphql.schema.SchemaUtil.replaceTypeReferences(SchemaUtil.java:141)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:110)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:104)
	at com.test.graphql.common.GraphQLTest.main(GraphQLTest.java:107)

**Comment by bbakerman** [comment] 2017-04-16 10:33
The cause is because type names in graphql MUST be unique.  However you have 2 objects with the same name but different types

    
    GraphQLInputObjectType otherDetailsInputObjectType = 
    GraphQLInputObjectType.newInputObject()
	.name("otherdetails")
	.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("key").build())
	.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("detail").build()).build();

    GraphQLObjectType otherDetailsObjectType = GraphQLObjectType.newObject()
	.name("otherdetails")
	.field(newFieldDefinition().type(GraphQLString).name("key").build())
	.field(newFieldDefinition().type(GraphQLString).name("detail").build())
	.build();

The type reference resolving at the end runs the map of all types by name and clashes on the name.

The base library probably should have a check BEFORE this stage so we can give a better  error message

**Comment by Priyank780** [comment] 2017-04-16 11:05
It means Graphql doesn't support same schema for read/write operation for this type of nested object schema? Should I use different name for reading and writing operation (bad solution basically)?

**Comment by kaqqao** [comment] 2017-04-16 12:19
It's not a bad approach, because input and output types are fundamentally different and calling them the same is needlessly convoluted. Output can contain interfaces, unions and potentially endless recursion. Inputs can have none of those. So it stands to reason you need to make distinct types for input and output, and distinct types should have distinct names. It is a common practice to have something like `otherdetails` and `otherdetails_input`.

**Comment by bbakerman** [comment] 2017-04-27 00:11
The spec says

     All types within a GraphQL schema must have unique names. No two provided types may have 
     the same name. No provided type may have a name which conflicts with any built in types 
     (including Scalar and Introspection types).

So you can have the same names.

**Comment by kaqqao** [comment] 2017-04-27 06:07
Why not close the issue? Nothing left to be said...

**Comment by bbakerman** [comment] 2017-04-28 02:19
Yeah I created a PR to better adddress this early

https://github.com/graphql-java/graphql-java/pull/390

**Closed by bbakerman** 2017-04-28 02:19 UTC
