### ISSUE TITLE
Possible data race in AsyncExecutionStrategy

### ISSUE THREAD

**Issue by Me1kaa** [graphql-java/graphql-java#1178] opened 2018-08-20 09:36 UTC
I use 2018-08-16T09-47-33-00a720f version(because of that fix https://github.com/graphql-java/graphql-java/pull/1113).

So: everything is okay, but sometimes(randomly) I face the exception that should never be thrown, according to code. I use DataLoaders and as a result DataLoaderDispatcherInstrumentation.

``` java 
java.util.concurrent.CompletionException: graphql.AssertException: Internal error: should never happen: level 3 already dispatched
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at graphql.execution.Async.lambda$each$0(Async.java:38)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: graphql.AssertException: Internal error: should never happen: level 3 already dispatched
	at graphql.Assert.assertShouldNeverHappen(Assert.java:26)
	at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach$CallStack.dispatchIfNotDispatchedBefore(FieldLevelTrackingApproach.java:101)
	at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach.dispatchIfNeeded(FieldLevelTrackingApproach.java:235)
	at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach.handleOnFieldValuesInfo(FieldLevelTrackingApproach.java:177)
	at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach.access$000(FieldLevelTrackingApproach.java:32)
	at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach$1.onFieldValuesInfo(FieldLevelTrackingApproach.java:154)
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedExecutionStrategyInstrumentationContext.lambda$onFieldValuesInfo$2(ChainedInstrumentation.java:261)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedExecutionStrategyInstrumentationContext.onFieldValuesInfo(ChainedInstrumentation.java:261)
	at graphql.execution.AsyncExecutionStrategy.lambda$execute$1(AsyncExecutionStrategy.java:83)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	... 14 common frames omitted
```
The whole query is failed to execute when it happens. That happens very rarely, so, seems to be a data race somewhere in the code. 
Is it the known problem? I haven't found any open issues that match the problem. If it's not the known problem - I'll try to provide a minimal working example or test for reproducing.

**Comment by bbakerman** [comment] 2018-08-20 10:17
This is not a known problem.  if you can get a test reproduction that would be perfect

Perhaps @andimarek  we should just log and not throw exception??

**Comment by andimarek** [comment] 2018-08-21 09:16
I think this is a duplicate of https://github.com/graphql-java/graphql-java/pull/1179 .

**Comment by Me1kaa** [comment] 2018-08-22 08:53
@andimarek exactly, that's it. I close the issue.

**Closed** 2018-08-22 08:53 UTC
