### ISSUE TITLE
Batching performance of AsyncExecutionStrategy with DataLoader

### ISSUE THREAD

**Issue by essh** [graphql-java/graphql-java#760] opened 2017-10-08 03:05 UTC
I'm investigating moving from a BatchedExecutionStrategy to AsyncExecutionStrategy with DataLoader & DataLoaderDispatcherInstrumentation, especially if this is the better approach moving forward (based on https://github.com/graphql-java/graphql-java/issues/757#issuecomment-334618674). 

However, I haven't been able to reach anywhere near the same level of batching with the new setup. Batch sizes are 1 a majority of the time, or a handful of items at best compared to the huge batches I was able to achieve previously.

I've created a simple and rather crude demo at https://github.com/essh/graphql-java-batch-compare that compares BatchedExecutionStrategy with the DataLoader approach. In the sample output you can see that the the batch size is always small (in this case a single item).

https://github.com/graphql-java/graphql-java/issues/757#issuecomment-334945100 also seems to be having similar problems.

**Comment by bbakerman** [comment] 2017-10-08 22:07
Thanks for reporting this with such detail.  I think you have found a problem in our implementation

I have forked your repo and am working on it currently to look into the problem

Your query is

    query { 
        shops { 
              id 
              name 
              departments { 
                  id 
                  name 
                  products { 
                       id 
                       name 
                  } 
              } 
         } 
    }

Early analysis says that the problem maybe in `graphql.execution.ExecutionStrategy#completeValueForList`.   This is the code that completes a list of values, in this case a list of "shops"

The implementation is to run completeValue for each item in the list.  However in practice this runs the execution engine down a level per list item.  This in turns cause the dispatcher to dispatch per list item and not for the whole list.

This is my early theory by the way.  I havent fully confirmed this.

What I expect to happen is this

- engine encounters a list of shops
- for each shop it creates a promise to resolve that shop item
- at the end of the 'shops' field then dispatchAll() is called to make good on those promises
- this would cause department loads for the shop departsments

I will look into this more.  Once again thank you for reporting in such detail.

**Comment by bbakerman** [comment] 2017-10-08 22:09
I have a request from you @essh - In order to fix this issue I am going to need test case data.

Can we please use the code in your example repo as the basis for that test case.  It will save  alot of work since you have done the heavy lifting in reproduction on this.

**Comment by essh** [comment] 2017-10-08 22:12
Sure, I'm fine with that.

**Comment by bbakerman** [comment] 2017-10-09 21:02
OK I had a deeper look at this.  First off lets explain the data

```
                shops: [
                        [id         : "shop-1", name: "Shop 1",
                         departments: [[id: "department-1", name: "Department 1", products: [[id: "product-1", name: "Product 1"]]],
                                       [id: "department-2", name: "Department 2", products: [[id: "product-2", name: "Product 2"]]],
                                       [id: "department-3", name: "Department 3", products: [[id: "product-3", name: "Product 3"]]]
                         ]],
                        [id         : "shop-2", name: "Shop 2",
                         departments: [[id: "department-4", name: "Department 4", products: [[id: "product-4", name: "Product 4"]]],
                                       [id: "department-5", name: "Department 5", products: [[id: "product-5", name: "Product 5"]]],
                                       [id: "department-6", name: "Department 6", products: [[id: "product-6", name: "Product 6"]]]
                         ]],
                        [id         : "shop-3", name: "Shop 3",
                         departments: [[id: "department-7", name: "Department 7", products: [[id: "product-7", name: "Product 7"]]],
                                       [id: "department-8", name: "Department 8", products: [[id: "product-8", name: "Product 8"]]],
                                       [id: "department-9", name: "Department 9", products: [[id: "product-9", name: "Product 9"]]]]
                        ]]

```

This is the underlying data in the shop /department / product database, using the query above.

One thing to note is that its *perfectly* spread.  That is shop 1 has unique departments with unique products as does shop2 and shop3.  So there is no caching available.

@essh - that is one thing to note - that is in the real world one would expect some overlap and hence caching would kick in and no data fetches would be made for items previously fetched.  So the data is quite pathological in this case.

So above we get 3 batch calls for departments (one per shop) and 9 batch calls for products (one per department)

The reason for this is the graphql-java list handling.  When it encounters a list (say of shops) it iterates each item and calls `completeValue` for each which calls `executionStrategy.execute()` and resets the whole call stack down one level.

So the DataLoaderRegistry.dispatchAll() is being called when you go down to that level and fetch+resolve 1 or more fields.  

So above the list of shops, it descends on shop1 and tries to resolve id/name and departments but because it eagerly calls `execute` again it means dispatch is called and hence the batch fires.

It would have to do a breadth first approach to lists to avoid this I think.

I am still investigating how we can fix this without fundamentally rearranging the execution order.

**Comment by bbakerman** [comment] 2017-10-12 07:17
I have a fix and it gets the performance back on par with BatchedExecutionStrategy (but with more correctness as a graphql query that is)

**Comment by szantogab** [comment] 2017-10-17 08:46
@bbakerman Any info on when this will be merged?

**Comment by aruberto** [comment] 2017-10-18 20:46
I was trying out the changes in the pull request but still running into issues once I am past first level. 

I'll see if I can create a working example of issue later but a similiar schema to what I am working with would be:

```
type Company {
  id: Int!
  name: String!
}

type Person {
  id: Int!
  name: String!
  company: Company!
}

type Product {
  id: Int!
  name: String!
  suppliedBy: Person!
}

type QueryType {
  products: [Product!]!
}
```

I have BatchLoader and DataLoaders hooked up for the suppliedBy and company lookups. When I query:

```
query Products {
  products {
    id
    name
    suppliedBy {
      id
      name
      company {
        id
        name
      }
    }
  }
}
```

The suppliedBy resolving correctly calls the BatchLoader with all the person ids. However the company BatchLoader gets called multiple times with a single key each time.

**Comment by bbakerman** [comment] 2017-10-19 02:10
Can you post a unit test / code showing this please

**Comment by aruberto** [comment] 2017-10-19 06:58
@bbakerman I've created an example project - https://github.com/aruberto/graphql-java-dataloader-issue

With graphql-java 5.0, running main method produces 100 lines each of `PERSON BATCH LOADER STARTING WITH 1 KEYS!` and `COMPANY BATCH LOADER STARTING WITH 1 KEYS!`

With graphql-java built from https://github.com/bbakerman/graphql-java/tree/760-dataloader-performance-with-lists, the person batch loader is only called once and the app prints `PERSON BATCH LOADER STARTING WITH 100 KEYS!` but afterwards it calls company batch loader 100 times and prints 100 `COMPANY BATCH LOADER STARTING WITH 1 KEYS!`

**Closed** 2017-11-05 22:08 UTC

**Comment by essh** [comment] 2017-11-16 09:08
Thanks for this work. I’ve had a chance to test it out now and it is much better than before but still not quite as efficient as the BatchedExecutionStrategy. The previous comment on this issue also raised this point with an example and the test cases added with the fix also seem to indicate it’s not quite on the exact same level yet.

Any thoughts on what could possibly be done on top of this work to further improve batching performance as you move deeper into the query?

**Comment by vojtechhabarta** [comment] 2018-03-13 21:34
I have the same problem.
Currently I am using `BatchedExecutionStrategy` and I wanted to switch to `AsyncExecutionStrategy` but it is much slower in my case and for larger data (where `BatchedExecutionStrategy` finishes its job in 30 seconds) `AsyncExecutionStrategy` fails after few minutes with `OutOfMemoryError`.

My data structure is like this: `P -> [D] -> [A] -> H`.

Arrays of `A` objects work well, they are loaded using one batched request for all `D` objects at once.
But when loading `H` objects `DataLoader` is dispatched separately for arrays of `A` objects "belonging" to one `D` object at a time.

So for example let's say I have 100 `D` objects and each has 10 `A` objects. With `BatchedExecutionStrategy` only one request for 1000 `A` objects is sent to backend but with `AsyncExecutionStrategy` 100 requests are sent.

(using graphql-java 7.0)
