### ISSUE TITLE
Interface subtypes in IDL disappear

### ISSUE THREAD

**Issue by piotrblasiak** [graphql-java/graphql-java#544] opened 2017-07-03 13:40 UTC
if I define subtypes to an interface in IDL they disappear from schema.getAllTypesAsList() and are not available for queries.

```
schema {
  query: QueryRoot
}

type QueryRoot {
  products: [Product]
}

interface Product {
  name: String!
}

type SubscriptionPlan implements Product {
  name: String!
  numDays: Int!
}

```

The workaround, as it seems the types are somehow garbage collected - is to add a reference to them like this (see dummySubscriptionPlan QueryRoot):

```
schema {
  query: QueryRoot

  dummySubscriptionPlan: SubscriptionPlan # Workaround for type to be available
}

type QueryRoot {
  products: [Product]
}

interface Product {
  name: String!
}

type SubscriptionPlan implements Product {
  name: String!
  numDays: Int!
}

```

Then the type is available and it works.

**Comment by andimarek** [comment] 2017-07-04 19:05
@piotrblasiak What version of graphl-java are you using? This should be fixes in the latest dev build. It would be great if you try this, if you haven't already.

Thanks!

**Comment by andimarek** [comment] 2017-07-04 19:11
@piotrblasiak you can find informations how to use the lastest dev build here: http://graphql-java.readthedocs.io/en/stable/getting_started.html#using-the-latest-development-build

**Comment by bbakerman** [comment] 2017-07-05 09:50
This is a duplicate of https://github.com/graphql-java/graphql-java/issues/538 and is indeed fixed on master

**Closed by bbakerman** 2017-07-05 09:50 UTC

**Comment by piotrblasiak** [comment] 2017-07-05 12:46
Looks like it indeed is the same problem as #538. Will wait until it hits a stable build, thanks!
