### ISSUE TITLE
GraphQL Enum Value Description does not seem to be working properly

### ISSUE THREAD

**Issue by mkrouwer-lv** [graphql-java/graphql-java#167] opened 2016-06-17 15:43 UTC
The .value documentation for GraphQL Enum types suggests that there are three possible implementations, ranging from the simple .value("ENUM") to .value(String name, Object value, String Description).  The simple .value("ENUM") works fine, however when I try to use the later .value implementation so I can add a unique description for each enum value it doesn't work. It just shows the highest level description for the enum type, not the individual description for each enum value. I've posted what I see below in GraphiQL. Any help would be much appreciated
<img width="299" alt="screen shot 2016-06-15 at 2 21 54 pm" src="https://cloud.githubusercontent.com/assets/16542968/16156101/8a3f4310-3480-11e6-8d39-6e8992b46144.png">

So up above I would like unique descriptions for "MYSELF" and it's counterpart.

**Comment by andimarek** [comment] 2017-05-24 08:49
Hi @mkrouwer-lv,

I can't reproduce it. It  works fine as far as I can tell.

Do you still have this problem?

**Comment by andimarek** [comment] 2017-07-01 19:13
closing it for now, will be reopened if the problem still exists

**Closed by andimarek** 2017-07-01 19:13 UTC
