### ISSUE TITLE
Metadata support for schema type definitions

### ISSUE THREAD

**Issue by aschrijver** [graphql-java/graphql-java#183] opened 2016-07-30 10:19 UTC
As far as I see there is currently no support to add metadata to a schema definition.
Having a means to specify metadata on the various objects in `graphql.schema` package would allow additional server-side processing logic to be based on it.

I would like to propose adding `Builder.metadata(String, Object)` and `Builder.metadata(Map<String, Object> metadata)` methods to the various builder classes (and constructors), and having it available in data fetchers and type resolvers.

(Maybe instead of a `Map<String, Object>` the metadata could also be defined as a custom GraphQL introspection type `__METADATA`)

**Comment by IamCornholio** [comment] 2016-07-30 14:50
What kind of metadata would you add? Can you provide some examples?

**Comment by aschrijver** [comment] 2016-07-30 15:24
Yes, sure. 

The metadata will serve as a general extension mechanism that you can use in functionality that is not directly related to querying (i.e. `directives` are a means to add metadata to a query string). What it will be used for is entirely up to the client and depends on use case, etc.

Some of possible uses:
- Server / client-specific cache settings for individual schema objects
- Whether or not data can be asynchronously retrieved (but potentially unordered)
- Access restrictions for specific types
- Add `keywords` list and other stuff that don't neatly fit in `description` string
- Information regarding clustering, proxying (see below), encryption, compression, other server settings, etc.

A bit more information on my current use case: I am creating a remote service proxy for GraphQL schema's for use in microservices architectures (see [vertx-graphql-service-discovery](https://github.com/engagingspaces/vertx-graphql-service-discovery) and [vertx-graphql-schema-proxy](https://github.com/engagingspaces/vertx-graphql-schema-proxy). It works by marshalling a `GraphQLSchema` to JSON, and then rehydrating a proxy of it client-side.

This allows two styles of communication (or querying):
- Offload entirely to the back-end by sending it the query string and await the JSON result
- Invoke the schema proxy and execute at the client

The second option leads to a more chatty communication style where messages are sent to the backend for each `dataFetcher` and `typeResolver` that is encountered in query processing.
While more chatty, it allows asynchronous processing and fine-grained control of query distribution.

**Comment by aschrijver** [comment] 2016-07-31 17:15
As you can see I have moved the discussion to the specification level as well.

**Comment by dminkovsky** [comment] 2016-08-17 15:41
This is interesting and seems harmless enough. Except I am unaware of such functionality in any other implementation. That said, I only follow the JS implementation, so please let me know if I am wrong. A goal of this implementation is to follow the spec and to also be as familiar as possible to people coming from other implementations. 

Furthermore, a work-around for the absence of this feature exists: one can (ab)use the `description` property to store metadata. You might have to employ serialization/deserialization if your metadata is structured. But still, at this time, I think `description` fits the bill sufficiently for metadata.

So I am closing this for now to possibly revisit later.

**Comment by aschrijver** [comment] 2016-08-17 17:44
The metadata concept is indeed harmless. A similar, simple mechanism is used throughout Vert.x toolkit and gives a lot of freedom and flexibility.
As you saw I have added an issue to the graphql spec project, as I, like you, think a mechanism like this should be more or less standardized across implementations.
The solution with `description` is IMHO more hack than work-around (so its abuse :wink:). The description will in most cases already be used to generate API documentation anyway.

**Comment by aschrijver** [comment] 2016-08-17 21:00
Hi @dminkovsky ,

I see your general approach is to close issues that you intend to visit later (like https://github.com/graphql-java/graphql-java/issues/176 and https://github.com/graphql-java/graphql-java/issues/126).

Please, please, do not do that. Close should mean Done or WontFix. Not that you have memorized in the back of your head to revisit these issues later, or users should comb the closed issues list before they file a new issue. No one will ever check the list of closed issues to see which ones are _really_ closed and which may be closed only temporarily.

**Comment by dminkovsky** [comment] 2016-08-17 21:14
@aschrijver I see. I usually look through open and closed issues when searching for a topic. If the issue is closed, I check to see why it is closed. So I didn't know that there is a convention that Closed means Done or WontFix.

But yes, I can see how that might be confusing and counterproductive. So by that token, I guess this issue is re-opened, because this subject is by no means done or wontfix.

**Comment by dminkovsky** [comment] 2016-08-17 21:20
@aschrijver would #180 address this issue?

**Comment by aschrijver** [comment] 2016-08-17 21:25
Thanks :+1: 
There is not a specific convention, but like you said confusing. I think for most developers Closed means it is history, unless a team / project explicitly agrees to deviate from it (and with good reasons).

If the goal is to keep a clean, short backlog of issues, an alternative could be to maintain a wiki page 'Future plans' or something, and give indication what might be in future releases 2.1, 2.x, 3.x, etc.

#180 is a different issue. You can check out the project I created thus far (it is not finished) at: https://github.com/engagingspaces/vertx-graphql-service-proxy. You see the decorators are quite involved without clean interface implementations.

**Comment by aschrijver** [comment] 2016-08-17 21:27
BTW I might add the metadata support to my decorators, as I am now free to extend the API.

**Comment by kaqqao** [comment] 2017-06-03 08:01
@aschrijver What I do in these cases is use my own classes that extend the ones from the  `graphql.schema` package. Because my project maps Java to GraphQL dynamically, I store the class information with the types. Can also be used to store complexity information with the field definitions and such.

I like the proposed approach better, it is harmless and allows to stay within the library even in more exotic cases. The fact the reference implementation doesn't have a feature shouldn't​ really stop other implementations from innovating, right? Sangria has various features that the reference doesn't. [Absinthe](https://github.com/absinthe-graphql/absinthe) too.

**Comment by andimarek** [comment] 2017-06-04 19:28
@aschrijver Now that we support IDL schema definitions, would directives solve your Problem?

Not saying we will not add more support for custom metadata, I am just curios. 

I agree with @kaqqao: Not being implemented in the reference-implementation is no a reason to not add it. We will add what makes sense.

**Comment by aschrijver** [comment] 2017-06-05 10:07
Thanks @kaqqao , @andimarek ! I am not using IDL schema's at the moment, but I love the support for it in graphql-java. Great work!
Yes, I guess it could come a long way into supporting a proper metadata system.
This issue can be closed unless you have more plans with regards to metadata support (and there is also still the https://github.com/facebook/graphql/issues/200 open issue).

**Comment by emrul** [comment] 2017-07-07 02:53
I had the need for storing metadata on fields.  I did it by extending graphql.language.FieldDefinition with additional properties and passing that in to my builders.

In my data fetchers I can call environment.parentType.getFieldDefinition.getDefinition and check if its an instance of my subclass - if it is I can access the metadata to customise how my DataFetcher behaves.

The metadata I'm storing should never go to the client so I don't have to worry about serialising it.

**Comment by bbakerman** [comment] 2017-09-18 01:37
Added a PR for this in #716

**Comment by andimarek** [comment] 2019-05-14 09:46
I am closing this issue: We will not add completely arbitrary metadata to GraphQLSchema or Ast Nodes  because it would break immutability. 

But we recently added `Map<String, String>` to Field and will probably add it to every Node. See https://github.com/graphql-java/graphql-java/pull/1529 

Because that this PR is so old: if you have new input please open a new Issue. Thanks

**Closed by andimarek** 2019-05-14 09:46 UTC
