### ISSUE TITLE
Incompatible types in SchemaGenerator

### ISSUE THREAD

**Issue by zcourts** [graphql-java/graphql-java#1100] opened 2018-06-25 02:44 UTC
https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaGenerator.java#L499 is completely incompatible with https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaGenerator.java#L405

The returned type ref. from 405 can never be a `GraphQLInterfaceType` type. The result when this happens is a `ClassCastException`.

This happens in a case like this:
```
interface A{
 ...#some fields
}
type T1 implements A{
 f1: T2
}
type T2{
  f1: T3 
}
type T3 {
  f1: T1 #recursion - points to a T1
}
```

```
java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLInterfaceType
	at graphql.schema.idl.SchemaGenerator.lambda$buildObjectTypeInterfaces$9(SchemaGenerator.java:499)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaGenerator.buildObjectTypeInterfaces(SchemaGenerator.java:498)
	at graphql.schema.idl.SchemaGenerator.buildObjectType(SchemaGenerator.java:489)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:411)
	at graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:695)
	at graphql.schema.idl.SchemaGenerator.lambda$buildObjectType$6(SchemaGenerator.java:478)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaGenerator.buildObjectType(SchemaGenerator.java:477)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:411)
	at graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:695)
	at graphql.schema.idl.SchemaGenerator.lambda$buildObjectType$6(SchemaGenerator.java:478)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaGenerator.buildObjectType(SchemaGenerator.java:477)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:411)
	at graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:695)
	at graphql.schema.idl.SchemaGenerator.lambda$buildInterfaceType$12(SchemaGenerator.java:531)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaGenerator.buildInterfaceType(SchemaGenerator.java:530)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:413)
	at graphql.schema.idl.SchemaGenerator.lambda$buildAdditionalTypes$3(SchemaGenerator.java:365)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at graphql.schema.idl.SchemaGenerator.buildAdditionalTypes(SchemaGenerator.java:357)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchemaImpl(SchemaGenerator.java:332)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:274)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:246)
```

**Comment by zcourts** [comment] 2018-06-25 02:54
Some debugging shows this wasn't a problem in v8.0 because https://github.com/graphql-java/graphql-java/blob/v8.0/src/main/java/graphql/schema/idl/SchemaGenerator.java#L284 was being hit whereas it isn't in 9.0 and as a result https://github.com/graphql-java/graphql-java/blob/v8.0/src/main/java/graphql/schema/idl/SchemaGenerator.java#L290 gets hit instead which produces the type reference leading to this.

**Comment by bbakerman** [comment] 2018-06-25 08:35
Can  I ask what version of graphql-java you are on and perhaps to utilise a reproduce unit test

I created this quick unit test to try and reproduce and it could not

```
    def "#1100 - interfaces can be generated"() {
        def spec = '''
            interface A {
              interfaceField : String
            }
            
            type T1 implements A {
                interfaceField : String
                f1: T2
            }
            type T2 {
                f1: T3 
            }
            type T3 {
                f1: T1 #recursion - points to a T1
            }
            
            type Query {
                f : T1
            }
        '''

        def schema = schema(spec, TestUtil.mockRuntimeWiring)

        expect:
        schema != null
    }
```

Can you please try to reproduce this further

**Comment by bbakerman** [comment] 2018-06-25 08:41
The class `graphql.schema.idl.SchemaTypeChecker` is meant to pre-validate that type structure is valid by the way and hence we later make some assumptions about things being ok to cast...

I say this as way of explaining the code - I am sure they could be bugs

**Comment by bbakerman** [comment] 2018-06-28 23:29
Thanks

**Comment by bbakerman** [comment] 2018-07-24 06:33
Since there is no reply I am going to close this issue for now

**Closed by bbakerman** 2018-07-24 06:33 UTC
