### ISSUE TITLE
`MaxQueryDepthInstrumentation` and `MaxQueryComplexityInstrumentation` fail with __typename

### ISSUE THREAD

**Issue by drewolson** [graphql-java/graphql-java#669] opened 2017-08-30 16:15 UTC
A null pointer exception is thrown on [this line](https://github.com/graphql-java/graphql-java/blob/499b37c301317efc36602bb1b8c84d3d4a0ab93b/src/main/java/graphql/analysis/QueryTraversal.java#L90) when the type being traversed is an interface.

**Comment by andimarek** [comment] 2017-08-30 16:25
@drewolson could you post an example query? thanks

**Comment by drewolson** [comment] 2017-08-30 16:30
I'm working on a PR now. If nothing else, I should at least be able to provide a failing test. Will update this issue once I've got it.

**Comment by drewolson** [comment] 2017-08-30 16:50
I wrote a failing test in my fork [here](https://github.com/drewolson/graphql-java/commit/c142a3f9f28cd343aed91d0a89c518f26d5da5bd). The problem is [this line](https://github.com/drewolson/graphql-java/blob/c142a3f9f28cd343aed91d0a89c518f26d5da5bd/src/test/groovy/graphql/analysis/QueryTraversalTest.groovy#L125). The fact that the `selectionSet` is `null` is causing the null pointer exception.

I'll poke around and see if I can find a solution but I'm guessing you may know the fix faster than I do.

**Comment by andimarek** [comment] 2017-08-30 17:30
@drewolson I can't reproduce it. I modified the test a bit and it is green now: https://gist.github.com/andimarek/841b539fa199d4c8d7a2b445442329c4

**Comment by drewolson** [comment] 2017-08-30 18:04
@andimarek The point is that the `selectionSet` _is null_ but it _should not be_. The null `selectionSet` for `interfaces` is blowing up when it calls [this line](https://github.com/graphql-java/graphql-java/blob/499b37c301317efc36602bb1b8c84d3d4a0ab93b/src/main/java/graphql/analysis/QueryTraversal.java#L90).

**Comment by andimarek** [comment] 2017-08-30 18:22
@drewolson yes, please try to come up with a failing test where the NPE occurs ... thank you.

**Comment by drewolson** [comment] 2017-08-30 18:47
Here's the simplest example I could come up with that explodes.

https://github.com/drewolson/graphql_npe_example/blob/master/src/test/java/NpeExampleTest.java

**Comment by andimarek** [comment] 2017-08-30 23:09
@drewolson thank you for creating the example test. 

This is indeed a bug, but it is a problem with the instrumentation, rather than with  `QueryTraversal` itself.  This PR should fix this: #670

**Comment by andimarek** [comment] 2017-08-30 23:13
@drewolson Just to be clear:

The root problem is that your query itself is not valid: You can't query `{a}` if `a` is an Interface: you have to select one or more subfields.

**Comment by drewolson** [comment] 2017-08-31 15:24
@andimarek my apologies, it appears that `interface` was a red herring. The actual cause of my NPE is the introspection field `__typename`. I've updated my [example](https://github.com/drewolson/graphql_npe_example/blob/cbe9cf08f6f173188e70b6e5a3d344e1513779d8/src/test/java/NpeExampleTest.java) to demonstrate the problem. I hope this helps! Thanks for your responsiveness.

**Comment by andimarek** [comment] 2017-09-02 09:07
Thanks for reporting: This #682 should fix it.

**Comment by drewolson** [comment] 2017-09-02 13:42
Thanks! Any chance in getting this on a 4.2 release? This bug completely breaks GraphiQL when using instrumentation.

**Comment by andimarek** [comment] 2017-09-02 13:45
maybe .. we haven't planned it yet.

But you could you please test it before we release it?

After the PR is merged you just have to use the latest dev build: http://graphql-java.readthedocs.io/en/v4/getting_started.html#using-the-latest-development-build

**Comment by drewolson** [comment] 2017-09-02 13:46
Yes, will do.

**Comment by andimarek** [comment] 2017-09-06 23:56
@drewolson it is merged .... could you try the latest dev build? Thank you!

**Comment by drewolson** [comment] 2017-09-07 14:01
I have confirmed that this fix works for me, thanks!

**Comment by andimarek** [comment] 2017-09-08 01:14
@drewolson thanks ... closing this issue now: the fix will be in the next release

**Closed by andimarek** 2017-09-08 01:14 UTC
