### ISSUE TITLE
GraphQL best practices for high performance data fetching from database?

### ISSUE THREAD

**Issue by ieugen** [graphql-java/graphql-java#441] opened 2017-05-16 19:44 UTC
Hello, 

How can I improve performance of GraphQL queries? This is a general question, I know. I'm looking for best practices on how to implement GraphQL with graphql-java. 

I have a simple schema: 

````
type Account @java(package:"com.example") {
  id: ID!
  users: [User]!
}

type User @java(package:"com.example"){
  id: ID!
  email: String!
  firstName: String
  lastName: String
}
````

Making the following query: 

````
{
  accounts {   id   users {   id  }   }
}
````
takes around ~19s -> ~50s on my machine and the staging server to produce: [query-results.txt](https://github.com/graphql-java/graphql-java/files/1005642/query-results.txt)

Data is fetched from a database with a code that looks like this: 

````
    @Override
    public List<Account> getAccounts() {
        List<gr8pi.web.platform.Account> allAccounts = accountRepository.findAll();
        return allAccounts.stream().map(a -> {
                List<gr8pi.web.candidate.Respondent> respondents = respondentRepository.findAll();

                List<Membership> memberships = membershipRepository.findByAccountId(a.getId());

                List<User> users = memberships.stream()
                    .map(membership -> new User.Unresolved.Builder()
                        .withId(Long.toString(membership.getUser().getId()))
                        .withEmail(membership.getUser().getEmail())
                        .withFirstName(membership.getUser().getFirstName())
                        .withLastName(membership.getUser().getLastName())
                        .build())
                    .collect(Collectors.toList());

                return new Account.Builder()
                    .withId(Long.toString(a.getId()))
                    .withRespondents(Collections.EMPTY_LIST)
                    .withUsers(users)
                    .build();
            }
        ).collect(Collectors.toList());
    }

````

I'm using spring data repository and hibernate 5.2 and the database is PostgreSQL. The code is very simple and I do believe some improvements can be made, but the point is, in my opinion : **you can't get away without making a lot of calls to the database**. 

My question is: **What are the best practices on implementing good performing data fetching from database systems.**

Thanks,

**Comment by bbakerman** [comment] 2017-05-18 09:35
In this case you can get away without making a lot of calls.

Some graphql "graphs" force a lot of calls and hence require sophisticated techniques such as DataLoader to alleivite this.  

But in your example here you can make your code MUCH more efficient and its nothing to do with graphql and everything to do with SQL

```
List<gr8pi.web.platform.Account> allAccounts = accountRepository.findAll();
        return allAccounts.stream().map(a -> {
                List<gr8pi.web.candidate.Respondent> respondents = respondentRepository.findAll();

                List<Membership> memberships = membershipRepository.findByAccountId(a.getId());
```

The problem is you are doing n+1 SQL calls.  For every account do an SQL to get all respondents
(over and over again - thats really wasteful) and then membership information.

I think you need to revist your "database design.

You want to use SQL joins and get accounts joined to membership and respondants.  Let SQL to all the heavy lifting for you in a lot less calls (maybe even 1)

I dont know the ins and out of your database design but SQL joins are what you want here to reduce the dreaded N+1 performance problems.

And in this case its not graphql induced.

Where graphql can get hairy is graphs all the way down

eg


    query socialNetwork {
        name
        friends {
           name 
           friends {
             name
          }
     }

The above is find a person and their friends and their friends friends.  This is hairy.

**Comment by ieugen** [comment] 2017-05-18 09:50
Thanks @bbakerman, I think exposing good models and making the queries fit that model is a good way of achieving good performance. Also graphql maps very good to CQRS and Event Sourcing so I imagine that we can use projections that fit the response we need to send to the end user. But that takes a lot of effort to design properly and it will happen in time. 

Some other tricks I found is that for example, all big players that expose an API do automatic paging of results. Github pages to 30 by default with a maximum of 100 items per page [1] . Amazon AWS does something similar. 

Come to think of it, it is unreasonable not to do some form of pagination automatically. This will limit the number of results fetched and consequently the number of calls to the database that cascade.

Building projections is a more advanced topic but can yield real benefits. 

p.s. I managed to reduce the time it took the query to ~6s by tweeking the code and making the calls to the users in the User Data fetcher. Still n+1 trips to the database, but it works faster. Don't know why right now but it is enough for us to adopt graphql internally.  


[1] https://developer.github.com/v3/#pagination

**Comment by bbakerman** [comment] 2017-05-18 23:14
In terms of pagination in graphql, this is your responsibility as a schema designer.

The list fields you give back can contain "pagination" arguments and pagination "info"

The Relay specification has pagination built in : https://facebook.github.io/relay/docs/graphql-connections.html

This also outlines some ways to do pagination : http://graphql.org/learn/pagination/

The point is pagination is not a graphql engine thing - its the schema designers repsonsibility

**Comment by bbakerman** [comment] 2017-05-18 23:16
Also have a look at idea behind DataLoader : https://github.com/facebook/dataloader

It allows for combining common look ups into less calls (if it suits your app)

There is a java implementation : https://github.com/engagingspaces/vertx-dataloader

I havent used the above one however

**Comment by andimarek** [comment] 2017-05-20 02:31
@ieugen closing it, because it seemed answered.

**Closed by andimarek** 2017-05-20 02:31 UTC
