### ISSUE TITLE
Support for Java Modules

### ISSUE THREAD

**Issue by MohammedAtif** [graphql-java/graphql-java#1604] opened 2019-07-16 07:32 UTC
**Describe the bug**
Current version of graphql-java does not support Java modules

**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.
1. Create a spring boot project
2. Change project SDK to Java 9 or above. I use Java 11 (Amazon Coretto OpenJDK)
3. Add and update module-info.java to support Java modules
4. Add graphql-java dependency as mentioned in [this demo](https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/)
5. Run the application using IDE.
6. Following errors pop up

`Error:java: module lombok reads package graphql.spring.web.servlet from both graphql.java.spring.boot.starter.webmvc and graphql.java.spring.webmvc`

There are more than 100 such error for different packages. Attaching image for reference.

![image](https://user-images.githubusercontent.com/19682568/61274612-c95b9c00-a7c9-11e9-9a15-afb85fa2cd8e.png)

**Comment by andimarek** [comment] 2019-07-16 07:39
I am not sure this is a direct problem of graphql java: this ist the core library which executes a query. I can only see spring, jackson etc messages. 

But we are not doing anything specific to support java modules, so there still might be some support missing: could you be more specific what this library should provide? thanks

**Comment by ieugen** [comment] 2019-07-19 12:30
Hi @MohammedAtif ,

graphql-java has very few dependencies, spring and jackson are not among them.
Full list https://github.com/graphql-java/graphql-java/blob/master/build.gradle

I believe the issue is not with graphql-java. Maybe something else, above it. 
```
    compile 'org.antlr:antlr4-runtime:4.7.2'
    compile 'org.slf4j:slf4j-api:' + slf4jVersion
    compile 'com.graphql-java:java-dataloader:2.1.1'
    compile 'org.reactivestreams:reactive-streams:' + reactiveStreamsVersion
```

**Comment by bbakerman** [comment] 2019-08-23 08:33
I am going to close this as not a graphql-java problem

**Closed by bbakerman** 2019-08-23 08:33 UTC
