### ISSUE TITLE
Wrong InvalidSyntaxError message

### ISSUE THREAD

**Issue by pklozik-vendavo** [graphql-java/graphql-java#3303] opened 2023-08-26 19:46 UTC
**Describe the bug**
When you parse an invalid schema the syntax error has the wrong prefix
**To Reproduce**
1) Parse schema (as an invalid string) e.g. schema = "data_load/customerA_test.graphql"
SchemaParser().parse(schema)
2) Check the error message: "Invalid Syntax : Invalid syntax: token recognition error at: '/' at line 1 column 10"

Result
Expected Error prefix:   "Invalid Syntax:"
Actual Error prefix:        "Invalid Syntax : Invalid syntax:"

**Comment by dondonz** [comment] 2023-08-27 23:36
Hi @pklozik-vendavo thanks for the report. Which version of graphql-java are you using?

**Comment by bbakerman** [comment] 2023-08-27 23:56
SchemaParser (along with SchemaGenerator) return a `graphql.schema.idl.errors.SchemaProblem` exception

Since many things could go wrong (in parsing and generation) its an exception with multiple errors possible which you can get via `graphql.schema.idl.errors.SchemaProblem#getErrors`

The error you see above is the combined message.

Its actually

```
 errors=[InvalidSyntaxError{ message=Invalid syntax with offending token 'data_load' at line 1 column 1 ,offendingToken=data_load ,locations=[SourceLocation{line=1, column=1}] ,sourcePreview=data_load/customerA_test.graphql
```
which is not really meant to human read other than to say there are 1 or more underlying errors

I am closing this issue as its working as designed

**Closed by bbakerman** 2023-08-27 23:56 UTC
