### ISSUE TITLE
Question: Building GraphQL microservices and querying it from graphql-java server

### ISSUE THREAD

**Issue by mrcasablr** [graphql-java/graphql-java#1032] opened 2018-05-05 03:54 UTC
Hello,

We are embarking on using GraphQL for new microservices built on Spring Boot while existing ones are on REST API.  We want to use graphql-java as an apigateway server that will query REST API backends.  Can graphql-java also query graphql microservices directly?

Would I need a GraphQL java client (android java apollo client) on the graphql-java apigateway server to query graphql directly?

**Comment by huangd0ng** [comment] 2018-05-09 13:09
We are doing something like that. We build services based on Spring Cloud which provides restful api and use graphql for client queries. I built a library like feign using annotations to define how to fetch data from backends and create data loaders automatically. To answer your question, we use restful api between services and connect them in the graphql gateway. At client side, we use apollo client.

**Comment by bbakerman** [comment] 2018-05-10 07:36
graphql-java itself does not HTTP and is not a complete engine like say Tomcat + Spring etc....

You wire in data fetchers and they get data from some where.

You can put HttpClient calls behind these data fetchers and act as an API gateway to those REST services under one logical schema.

You might want to look at other libraries to give you a complete HTTP engine + JSON + logging + metrics etc... eg spring boot or dropwizard + the graphql-java library

Say https://github.com/graphql-java/graphql-spring-boot perhaps

**Comment by mrcasablr** [comment] 2018-05-10 12:35
@bbakerman Thank you! Yes, we will need a engine for sure. My question was more of if graphql-java can fetch data from a graphql source (a microservice).  For example - 

![graphql-microservice](https://user-images.githubusercontent.com/22866157/39869764-64079224-547c-11e8-89fd-9ec94b418bb2.png)

In the above picture, microservice 4 runs a graphql-java server on spring-boot so does api-proxy. I was wondering if the api-proxy graphql-java can talk to a graphql microservice built on graphql-java or we need a graphql java client on the api-proxy?

**Comment by bbakerman** [comment] 2018-05-11 06:48
graphql-java is a library that sets up the graphql query to follow the spec and handles all the interpretation.

The data fetchers are the thing you write yourself.  They are the places you get data from.  That might be a database call, a REST call or indeed another graphql downstream call.

That code is entirely up to you.  graphql-java has no network code that gets your our to another server say.

So your diagram above is entirely possible (we do exactly that in some services at Atlassian where I work) but you must code the data fetchers and do any "mapping between" what the downstream source gives you and what you want to send back in terms of your "gateway" schema.

If they are the same, then there is no mapping... If you want to present a modified view, then yeah tyou need some mapping code as well of results... along with data fetchers to get downstream data

**Comment by bbakerman** [comment] 2018-05-11 06:51
So specifcally - yes you will need a http client in "api proxy" to talk to the back end systems.

You dont need a specific graphql http client... Its just not the complicated in my opnion.  Lots of people think they MUST need a dedicated client.  But its so simple just hand code it using Apache Http client and be done

**Comment by bbakerman** [comment] 2018-05-20 09:42
I am going to close this issue as its a question and not a bug

**Closed by bbakerman** 2018-05-20 09:42 UTC

**Comment by lleraromero** [comment] 2020-02-20 21:41
I found https://github.com/graphql-java/graphql-java/issues/422 really useful to see an actual implementation of what @bbakerman, I believe, was referring to.
