### ISSUE TITLE
Errors and Non-Nullability

### ISSUE THREAD

**Issue by DomKM** [graphql-java/graphql-java#350] opened 2017-03-24 21:35 UTC
graphql-java does not currently handle [this section of the GraphQL spec](https://facebook.github.io/graphql/#sec-Errors-and-Non-Nullability) correctly.

"Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field."

graphql-java throws `graphql.GraphQLException: Cannot return null for non-nullable type` instead of propagating up to the parent field.

**Comment by dminkovsky** [comment] 2017-03-24 22:46
Thanks for opening this issue. Your observation is clearly correct and is
something I hope is fixed soon: either by me or by a PR from someone else.
This is also related to #268.

I suspect this will be fixed in 3.0 as part of the transition to Java 8
(see related issue #338)

Related is that errors do not list the field path that caused the error.
That is in part because this implementation does not track field path
during execution.






пт, 24 марта 2017 г. в 17:35, Dom Kiva-Meyer <notifications@github.com>:

**Comment by bbakerman** [comment] 2017-04-03 00:14
I think we should close this as a duplicate of #268 since its the same thing and use 268 as the fix ticket.  I have been looking at this one and its a curly one in code refactor terms

**Closed by bbakerman** 2017-04-03 00:14 UTC
