### ISSUE TITLE
graphql and spring and jpa 

### ISSUE THREAD

**Issue by liuzhijun123456** [graphql-java/graphql-java#305] opened 2017-01-20 09:42 UTC
Hello,
I now use the spring + springmvc + jpa integration framework. However, when I use the graphql in the framework, the use of jpa object inquiry mysql data, I get a null pointer error, you can tell me how to use? I am anxious to solve this problem.
please ,look at my java code.
![default](https://cloud.githubusercontent.com/assets/8455449/22144165/bfa2fc24-df37-11e6-8274-8dd14520fffe.PNG)

**Comment by mrcirillo** [comment] 2017-01-24 00:06
Could you post the request body that your browser is sending?

**Comment by bbakerman** [comment] 2017-03-22 08:07
I am tempted to close this issue as its not been actioned and is mostly an ask for general help not a bug / feature of the library

**Comment by andimarek** [comment] 2017-04-07 14:57
closing the issue as suggested by @bbakerman

**Closed by andimarek** 2017-04-07 14:57 UTC
