### ISSUE TITLE
Performance of ExecutionStrategy#completeField and ExecutionStrategy#fetchField

### ISSUE THREAD

**Issue by PoemDaga** [graphql-java/graphql-java#2017] opened 2020-08-31 10:09 UTC
Hi, 

While testing our application for 1k data, in the JProfiler readings we see graphql parsing and processing is taking significantly more time than the DB layer. 

![image](https://user-images.githubusercontent.com/65411246/91705979-5a8efd00-eb9b-11ea-9ebd-51438c81f7f5.png)

Specifically two methods:
-  graphql.execution.ExecutionStrategy#completeField
-  graphql.execution.ExecutionStrategy#fetchField

![image](https://user-images.githubusercontent.com/65411246/91706562-2e27b080-eb9c-11ea-8c80-a662a27fcda4.png)
**_*marked in blue is the Datafetcher implementation that looks up data from DB, taking 13.4% of the total execution time_**
**Note**: the output of DataFetchers is Map<String, Object> 

- Query used for this call:
```
{
  "query": "query searchEntities($scope: SearchScope!,$first: Int!,$sortBy: SortByField) {searchEntities(scope: $scope,first:$first,sortBy: $sortBy) {matchedEntities { activeEntity {  name description } draftEntities{ description probableEntity{ description name createTime }  }} pageInfo { endCursor hasNextPage } } } ",
  "variables": {    
	"scope": {
      "appIdentifier": "app1",
      "nativeType": "nativeType1"
    },
    "first":1000,
    "sortBy":{
    	"field":"UpdateTime",
    	"order":"Desc"
    }
  }
}
```

We are using graphql-java version : 14.0. Also attaching graphql schema.
[EntityApi.graphql.txt](https://github.com/graphql-java/graphql-java/files/5149705/EntityApi.graphql.txt)

-------------------------
- looking up 65k records, total Graphql execution took about 228s 
   > where actual DB lookup took ~22s only
![image](https://user-images.githubusercontent.com/65411246/91720055-09d7ce00-ebb4-11ea-8601-3f1ef25aa18f.png)

**Question is** : What factors contribute to graphql processing overhead? Are there any best practices that can help to reducing the overall time as we are extensively using graphql in all our APIs?

**Comment by JoseAlavez** [comment] 2020-09-01 08:33
We are seeing a similar situation in a tool we built to track down data fetchers performance: 
![image](https://user-images.githubusercontent.com/2037281/91826289-a5f9e780-ec3d-11ea-9595-e1cb342b4e57.png)

There are huge pauses after collecting data from other services / db. Answering this question will be super beneficial to all of us. We use `AsyncExecutionStrategy`.

**Comment by bbakerman** [comment] 2020-09-07 12:11
Let me unpack this a little

> we see graphql parsing and processing is taking significantly more time than the DB layer.

It will be processing.  The parsing of queries (in all but massive ridiculous queries) is lightning fast.  Dont worry about parsing.

> FetchField and CompleteField

`FetchField` is the code that invokes the DataFetchers - that is the your code callbacks or often the POJO reading PropertyDataFetcher (the default)

You need to examine how your data fetchers work.  Do they use multiple threads?  Do they run in a single thread all together (the default if you dont use an Executor) one after the other?  Is there any synchronization problems here?

`CompleteField` is where the value has been fetched and the engine continues to process that value.  The engine is recursive so if there are "subselections" in thr query it will decend on that fetched object and invoke more "FetchField" code on its value.  

The objects that are returned by your data fetchers are turned into "map" results.  eg given

```
person {
    name
    age
}
``

Then it will fetch a person, descend on the properties of that object (name and age) and complete them by "fetching" values for those fields.  Hence the recursive approach.

Recent versions of graphql-java have improved the PropertyDataFetcher so it gets values on simple POJOS faster.  But it was never awful - just not as fast as it could be.

Another area of "time" is how you take the DB results and turn them back into in memory objects.  How are you doing that?  Are using some POJO / DTO type classes?  If so whats the de-serialisation mechanism (Hibernate / Jackson / Gson / something else??)

Look out for N+1 n the fetchers.  eg entity X leads to a list of Entity Ys - that can be a common problem.  I notice your entities have sub entities.

Is that a single request or a sample of a system under load.  For example I can see `QueryDirectivesImpl` taking 5900ms yet its a simple object instantiation

```
 public QueryDirectivesImpl(MergedField mergedField, GraphQLSchema schema, Map<String, Object> variables) {
        this.mergedField = mergedField;
        this.schema = schema;
        this.variables = variables;
    }
```

Of course text analysis of perf data is tricky without context.

For example whats the system load like?  228s to make a request is not fast and if the database calls only take 22s then this system MUST be either in CPU meltdown or garbage collection panic- there is no way the java code can take this long on an unloaded system.

For example recently I loaded a million rows of in memory and ran the engine over it (so its all our code and should be CPU bound) and it completes in 2.5 seconds

https://gist.github.com/bbakerman/920c8bfa01ea309fd598b41f370626b8

```
+2ms Building data...
+0ms Running query warmup...
+3824ms Finished query warmup...
+0ms Starting query...
+2143ms done
```

Of course this is single threaded call on a complete unloaded system.  My point is that the code will run over millions of objects reasonable fast when unloaded so load on the system is important to know.  Do you have any GC challenges?  Is the system pausing because of GC collections?

**Comment by artem-ag** [comment] 2020-10-15 00:15
I observe similar slowness as the author in the post. I have very big payload to return to the client (~200Mb uncompressed).
The timing is:
- under 15s to fetch all the data
- ~20-40s pause (ExecutionStrategy.completeField) is running
Query completes in 40-60 seconds.
I estimate my query invokes PropertyDataFetcher approximately 1 million times in process.

I have roughly the following in my schema:
```
type ListOfMaps @connection where one of the fields is results: Map!

type Map {
	entries: [KVP!]!
}

type KVP {
    key: String!
    value: String!
}
```
I'm trying to return a page of 1000 items, each item has a map with 500+ elements in it. There is nothing running on the machine besides GraphQL-java doing it's magic.

If you could advise how to modify AsyncExecutionStrategy to speed up processing for `List<POJO>` where it's known that POJO is final and won't be modified by any data fetcher that would be awesome.

**Comment by bbakerman** [comment] 2020-10-15 04:00
>  If you could advise how to modify AsyncExecutionStrategy to speed up processing for List<POJO> where it's known that POJO is final and won't be modified by any data fetcher that would be awesome.

I am not sure graphql is right for this use case.  The fact is the graphql execution model is that your have a tree of things and you run property fetchers over them (possibly with arguments) and that feeds into another lowel level set of fetchers.  This allows for high customisation.

The graphql engine holds things in memory to do this - it is not a streaming processor - so you 200MB is really too large based on memory pressure - imagine you have 100s of request per second at 200MB min of memory each?   OOM!

You can work around this if your determined by using a `Object` scalar.  This basically says - whatever I have in this object take as it as is.  See https://github.com/graphql-java/graphql-java-extended-scalars and the Object / JSON scalar

The problem with this of course is that the client can ask for "certain field".  Its REST all over again.  They get what they get.

Your 200MB payload feels a lot like a file.  Perhaps you would be better to  to deliver a graphql field which is a `link` to a URL to call back to get the data.  This would allow for streaming of the data anda reduce memory pressure

**Comment by artem-ag** [comment] 2020-10-15 04:25
Yeah, I understand your point. For scenarios where payload size is really not tolerable we do have async data fetching using csv files. In my scenario this would be rendered in a table for the user synchronously. If nothing else possible, we'd have to limit what can be done interactively. For example, if I reduce page size 10x, I will have GraphQL-java overhead reduced 10x. Still that would be 4-5 seconds. 5 seconds wait for UI to load is pretty long.
Overall 200Mb per request is fine, because that's p99.9 of what will be requested. Minority of the requests will require that.

I prototyped extremely hacky solution for my scenario. The code below reduced GraphQL-java latency delay from 18 seconds down to ~1.7 seconds. With changes to other methods I could get it down to 1.1 seconds. I understand that's super hacky and probably can't be generified.

The most interesting thing below is `.fieldValueInfos(fakeFieldValueInfoList.subList(0, completedResults.size()))`. From what I can tell fieldValueInfos is only used for reference counting and content is not important. If I instead for each entry of the list did `FieldValueInfo.newFieldValueInfo(OBJECT).fieldValue(CompletableFuture.completedFuture(new ExecutionResultImpl(v, null))).build()` - overall runtime increased by at least 7 seconds.
```
public class CustomAsyncExecutionStrategy extends AsyncExecutionStrategy {

    private static final FieldValueInfo fakeFieldValueInfo =
            FieldValueInfo.newFieldValueInfo(OBJECT)
                    .fieldValue(
                            CompletableFuture.completedFuture(new ExecutionResultImpl(null, null)))
                    .build();

    private static final List<FieldValueInfo> fakeFieldValueInfoList =
            Collections.unmodifiableList(Collections.nCopies(10000, fakeFieldValueInfo));

    @SuppressWarnings("FutureReturnValueIgnored")
    @Override
    protected FieldValueInfo completeValueForList(
            ExecutionContext executionContext,
            ExecutionStrategyParameters parameters,
            Iterable<Object> iterableValues) {

        Collection<Object> values = FpKit.toCollection(iterableValues);

        if (values.size() > 0 && values.iterator().next() instanceof KVPGraphQLObject) {
            List<Object> completedResults = new ArrayList<>(values.size());
            for (Object value : values) {
                if (value instanceof KVPGraphQLObject) {
                    LinkedHashMap<String, String> convertedEntry = new LinkedHashMap<>(2);
                    convertedEntry.put("key", ((KVPGraphQLObject) value).getKey());
                    convertedEntry.put("value", ((KVPGraphQLObject) value).getValue());
                    completedResults.add(convertedEntry);
                } else {
                    throw new IllegalStateException(
                            "Expected all objects in the list to be KVPGraphQLObject");
                }
            }

            ExecutionResultImpl executionResult = new ExecutionResultImpl(completedResults, null);

            return FieldValueInfo.newFieldValueInfo(LIST)
                    .fieldValue(CompletableFuture.completedFuture(executionResult))
                    .fieldValueInfos(fakeFieldValueInfoList.subList(0, completedResults.size()))
                    .build();
        } else {
            return super.completeValueForList(executionContext, parameters, iterableValues);
        }
    }
}
```

**Comment by bbakerman** [comment] 2020-10-15 04:29
>  The code below reduced GraphQL-java latency delay from 18 seconds down to ~1.7 seconds. With changes to other methods I could get it down to 1.1 seconds. I understand that's super hacky and probably can't be generified.

We will have a look into this.  Perhaps there is generalised savings to be made.

  However once you move into the territory of "changing how the execution works" then really you should be aiming to create your own ExecutionStrategy.  It may involve copy and pasting code BUT you get all the power to loose spec constraints and so on

**Comment by bbakerman** [comment] 2020-10-15 04:32
Note: In unreleased master we have support for `Stream and Iterators` which reduces memory pressure compared to holding `List<Pojo>` say

https://github.com/graphql-java/graphql-java/pull/2067

**Comment by artem-ag** [comment] 2020-10-15 04:42
> Note: In unreleased master we have support for `Stream and Iterators` which reduces memory pressure compared to holding `List<Pojo>` say
> 
> #2067
Thank you. Unfortunately there are breaking changes that make it incompatible with graphql-java-kickstart caused by removed @defer support and class renames.

Overall, I don't think this is caused by memory pressure on the machines. I tried running with -Xmx50g while having at least 40Gb free. This issue seems to be caused by thread context switching as futures are not free. Combined with volume of object allocations. And topped off by at least some instrumentations overhead. Though, I'm definitely not an expert in how GraphQL-java works.

**Comment by dfa1** [comment] 2020-10-15 05:45
@bbakerman @artem-ag in a pretty similar use-case, I used a "specialized" execution strategy too, in order to remove one level of recursive calls. 

IMHO we should formalize this approach by using Object as described here https://github.com/graphql-java/graphql-java-extended-scalars

**Comment by dfa1** [comment] 2020-10-15 05:48
@artem-ag if you have JDK11 you can try ´Map.of´ instead of ´LinkedHashMap´

**Comment by bbakerman** [comment] 2020-10-15 05:50
> IMHO we should formalize this approach by using Object as described here https://github.com/graphql-java/graphql-java-extended-scalars

Remember that there is no field selection in a `Object` scalar - so its not generally applicable at all

eg none of this

```
    someComplexField {
        just 
       these
       sub
       properties
      only
   }
```

**Comment by dfa1** [comment] 2020-10-15 05:58
good point, then is not a viable option in my use-case. Thanks for the reminder! :)

**Comment by artem-ag** [comment] 2020-10-15 17:28
Is it possible to use Object scalar while maintaining strongly typed schema? Or do I actually have to define "map: Object" in SDK for it to work?

**Comment by perkins4j2** [comment] 2020-11-12 13:30
> 好点，然后在我的用例中不是一个可行的选择。感谢您的提醒！:)

![image](https://user-images.githubusercontent.com/18566995/98945190-22a61d80-252d-11eb-8979-85d29da2270c.png)
![image](https://user-images.githubusercontent.com/18566995/98945229-2fc30c80-252d-11eb-80b4-efbef5dc2edc.png)
![image](https://user-images.githubusercontent.com/18566995/98945240-35b8ed80-252d-11eb-8f4d-157a4257ecee.png)

I meet same problem。

GraphQL cost many time in ExecutionStrategy schedule;But in loader ,I return fix object ：`return new FeatureResult();`

I really need your help。thank you。

**Comment by dfa1** [comment] 2020-11-19 18:48
perkins4j2 I'm sorry, somehow missed this comment. I would give a try to the latest version:

https://mvnrepository.com/artifact/com.graphql-java/graphql-java/2020-11-16T00-02-27-3dfeae3

**Comment by bbakerman** [comment] 2021-07-10 02:24
I am going t close this issue.  We have attackd the performance of the execution strategy quite a lot of late.

Any of the (very welcome) perf details above will not be out of date to the code.

We should raise new performance issues against the latest code at future points

**Closed by bbakerman** 2021-07-10 02:24 UTC

**Comment by pinguinjkeke** [comment] 2022-02-05 12:54
@bbakerman thanks for an explanation about `PropertyFieldResolver`.

We are using Kotlin in our project and it generates getter for every class field so `PropertyFieldResolver` is never used. The only way to make `FieldResolverScanner` to use `PropertyFieldResolver` is to annotate Kotlin class field with `@JvmField` annotation so it will not generate getter method.

Is there any other solutions?

**Comment by bbakerman** [comment] 2022-02-06 02:19
> We are using Kotlin in our project and it generates getter for every class field so PropertyFieldResolver is never used. 

Sorry I am not what that is - do you mean `graphql.schema.PropertyDataFetcher`

I am not sure what `FieldResolverScanner` is either - is this in some Kotlin graphql librray maybe?   of is this the kickstart toolset??

https://jar-download.com/artifacts/com.graphql-java-kickstart/graphql-java-tools/11.0.0/source-code/graphql/kickstart/tools/resolver/FieldResolverScanner.kt  ??

We dont maintain KickStart if it is?

you need to outline your stack more to for me to get insight

**Comment by pinguinjkeke** [comment] 2022-02-06 11:12
@bbakerman yes, we're using graphql java kickstart

**Comment by bbakerman** [comment] 2022-02-07 05:15
> we're using graphql java kickstart
 In which I dont know how it works and this project (graphql-java) does not support kick start.

Good luck with finding your answers
