### ISSUE TITLE
About RuntimeWiring Please tell me what I should do

### ISSUE THREAD

**Issue by szjzszjz** [graphql-java/graphql-java#1555] opened 2019-05-27 05:12 UTC
SchemaGenerator schemaGenerator = new SchemaGenerator();
        
        RegistryUtil.pathList.add("static/schema/schema.graphql");
        RegistryUtil.pathList.add(UserProvider.schema_path);
        RegistryUtil.pathList.add(BookProvider.schema_path);
        TypeDefinitionRegistry typeRegistry = RegistryUtil.registry();

        RuntimeWiring userWiring = UserProvider.buildRuntimeWiring(userDataFetcher);
        RuntimeWiring bookWiring = BookProvider.buildRuntimeWiring(bookDataFetcher);

        GraphQLSchema graphQLSchema= schemaGenerator.makeExecutableSchema(typeRegistry,  userWiring);

        this.graphQL = GraphQL.newGraphQL(graphQLSchema)
                .build();

the trouble is:
How do I combine userWiring  and bookWiring  to form graphQLSchema?
Thanks!

**Comment by bbakerman** [comment] 2019-05-27 08:28
Duplicate of #1553

**Closed** 2019-05-27 08:29 UTC
