### ISSUE TITLE
AsyncExecutionStrategy not asynchronous enough

### ISSUE THREAD

**Issue by NKozlov** [graphql-java/graphql-java#1497] opened 2019-04-10 09:31 UTC
**Describe the bug**
Default ExecutionStrategy is `AsyncExecutionStrategy`, but it doesn't work like I expect.
I will try explain. We have dataFetchers as follows:
```
private RuntimeWiring buildRuntimeWiring() {
        return RuntimeWiring.newRuntimeWiring()
                .type("QueryType", typeWiring -> typeWiring
                                .dataFetcher("person", environment -> {
                                    return new Person("Nik", 30);
                                })
                )
                .type("Person", typeWiring -> typeWiring
                        .dataFetcher("hello", environment -> {
                            Thread.sleep(2000);
                            return "Hello from Person";
                        })
                        .dataFetcher("allPets", environment -> {
                            Thread.sleep(2000);
                            return List.of("Sharik", "Cat 1", "Dog 2");
                        })
                )
                .build();
    }
```
How long `AsyncExecutionStrategy` will execute request like `{person{hello, allPets}}`? I expect about ~2 sec, but in actual, a sequential call of data fetchers is performed and step of execution looks like this:
- `fetching field '/person/hello'`
- waiting 2 sec, because `Thread.sleep(2000)`
- `field '/person/hello' fetch returned 'java.lang.String'`
- `completing field '/person/hello'...`
- `fetching field '/person/allPets'`
- waiting 2 sec, because `Thread.sleep(2000)`
- `field '/person/allPets' fetch returned 'java.util.ImmutableCollections$ListN'`
- `completing field '/person/allPets'...`
It executed about 4 sec in one Thread. So, `AsyncExecutionStrategy` not run dataFetchers in async mode. It's happens because in `graphql.execution.ExecutionStrategy#fetchField` we used blocking call `Object fetchedValueRaw = dataFetcher.get(environment);`, but we need use `CompletableFuture` mode.
Note! If we use `graphql.schema.AsyncDataFetcher#async(graphql.schema.DataFetcher<T>)` in dataFetchers, it works really asynchronously. 

If the described behavior is really wrong, then you need to replace the blocking call. Please comments it.

**Comment by bbakerman** [comment] 2019-04-12 04:29
The graphql java project has an aim to NEVER introduce any `Threading` into the runtime.  That is up to consumers of the library.

So the API signature we have is ready for true asynchronous systems and we "compose / combine" the tree of CompletableFuture responses correctly.

However we never start a thread by design.

Hence what you see out of the box is a serial system because that is how java CompletableFuture work without threading executors

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

If you data fetchers return a simple object OR a CompletableFuture that is completed on the calling thread then you will get a serial system.

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

As you found out if you use the AyncDataFetcher then you are in fact using a ExecutorService backed by a pool of threads

```
    public CompletableFuture<T> get(DataFetchingEnvironment environment) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return wrappedDataFetcher.get(environment);
            } catch (Exception e) {
                if (e instanceof RuntimeException) {
                    throw (RuntimeException) e;
                } else {
                    throw new RuntimeException(e);
                }
            }
        }, executor);
    }

```

`ForkJoinPool.commonPool()` is the executor in this case by default

You data fetchers don't need to be wrapped BTW.  If they do this then they are parallel

```
dataFetcher("hello", environment -> {
                            return CompletableFuture.supplyAsync(() -> { 
                               Thread.sleep(2000);
                               return "Hello from Person";
                           });
                        })
```

Another reason we don't start threads is that we can then be used in Reactive systems such as Project Reactor or RxJava.

In those frameworks the base platform controls the "scheduling" of work and hence if graphql-java started threads we would interfere with the proper running of reactive systems.

But since we use CompletableFuture everywhere then reactive systems can easily convert a `Mono` to a `CompletableFuture` and still retain their reactive non executor service based scheduling of work.

We have a couple of reactive systems here at Atlassian where I work that use graphql-java successfully.

So graphql-java is ready to be asynchronous and do work in parallel while leaving the choice of the pattern of parallelism to the implementer

(Contrast this to some java frameworks that start threads without controls and make you op into their opinionated work scheduling - I am looking at you early versions of Guava!)

**Comment by NKozlov** [comment] 2019-04-12 13:12
Thank you for the detailed explanation, it sounds very correct and logical. I hope that this issue will be useful to everyone who asks such a question as myself. May be the moment to include this explain in the graphql-java documentation? There it is not explained clearly in such detail and sounds in two ways, which is why I got into the code to understand how it's works.

**Comment by andimarek** [comment] 2019-05-14 09:35
closing it because it got answered

**Closed by andimarek** 2019-05-14 09:35 UTC
