### ISSUE TITLE
Excuse me, how to implement permission verification?

### ISSUE THREAD

**Issue by tianyafangcao** [graphql-java/graphql-java#994] opened 2018-03-25 11:03 UTC
Now, I want to implement the different fields that are returned based on the roles used.

**Comment by bbakerman** [comment] 2018-04-03 06:56
Today you must wire this into your data fetcher code by hand

     DataFetcher df = environment -> {
         SecurityContext ctx = environment.getContext():
         if (ctx.hasRole("manager",ctx.getCurrentUser() {
              return callDownStreamData(environment)
         } else {
              return null
        }
     }

You need to set up the "security context" outside when you start the graphql execution and pass it in via the "context"

We are working on a directives based approach right now that might make this easier to declare

See #1001

**Comment by bbakerman** [comment] 2018-04-05 06:35
Since this is not a bug I am going to close this issue

**Closed by bbakerman** 2018-04-05 06:35 UTC
