### ISSUE TITLE
Complex queries with many fields cause StackOverflowError in BatchedExecutionStrategy

### ISSUE THREAD

**Issue by haizz** [graphql-java/graphql-java#960] opened 2018-03-06 09:01 UTC
Apparently there is an overload of stack due to CompletableFuture.whenComplete chain: each field in query costs 5 stack frames. Therefore a number of fields in query is heavily limited by stack size.

Is there any way to fix this undesired behavior?

https://gist.github.com/haizz/92834c13200cdc7377ec8badff0ef505

**Comment by bbakerman** [comment] 2018-03-07 00:24
Can you post the offending query to give us more reproduce info

**Comment by haizz** [comment] 2018-03-07 14:24
@bbakerman https://gist.github.com/haizz/5df2091859253a04523979db03a25d1e

**Comment by andimarek** [comment] 2018-10-01 01:31
I am closing this issue because BatchedExecutionStrategy is deprecated by us and we recommend using Batched DataLoader: https://graphql-java.readthedocs.io/en/latest/batching.html 

Please open an new issue if you experience the same problem with the new approach.

Sorry for the long delay.

**Closed by andimarek** 2018-10-01 01:31 UTC
