### ISSUE TITLE
GraphQLNonNull and GraphQLList defining structural equality breaks Traverser.traverse()

### ISSUE THREAD

**Issue by sachindshinde** [graphql-java/graphql-java#1835] opened 2020-03-27 16:38 UTC
**Describe the bug**
Both `GraphQLNonNull` and `GraphQLList` define `equals()` as equality of the wrapped type. In `Traverser.traverse()`, visited nodes are stored in `TraverserState.visited`, which is a `HashSet`. 

Note that [Java `Set`s use `equals()` for equality-testing, and Java docs warn that mutating an object in a way that is visible via `equals()` while that object is in a `Set` results in undefined behavior](https://docs.oracle.com/javase/8/docs/api/java/util/Set.html).

There are two issues:
- In `Traverser.traverse()`, `visited` using `equals()` means that if you have multiple references to `GraphQLNonNull` or `GraphQLList` wrapping e.g. a particular `GraphQLObjectType` instance, that instance will be touched by `TraverserVisitor.enter()` once, and then never be touched by `TraverserVisitor.backRef()`. This means that if you were trying to e.g. replace a reference conditionally, it wouldn't always work (see the example below).
- In `GraphQLTypeResolvingVisitor`, `GraphQLNonNull` and `GraphQLList` nodes that wrap type references are mutated in a way that changes the result of `equals()` (specifically their type references are replaced with references to the actual type object). This mutation happens after said node has been added to the `visited` set, and accordingly this results in undefined behavior. Undefined behavior here means `Set` could throw, or there could be issues similar to above, where if you have multiple references to `GraphQLNonNull` or `GraphQLList` wrapping some `GraphQLTypeReference` object, then it won't get replaced.

**To Reproduce**
```java
TypeDefinitionRegistry typeRegistry = new SchemaParser().parse(
        "type Query {\n" +
        "    changeMe: [Foo]\n" +
        "    dontChangeMe: [Foo]\n" +
        "}\n" +
        "\n" +
        "type Foo {\n" +
        "    dummy: String\n" +
        "}\n"
);
RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring().build();
GraphQLSchema schema = new SchemaGenerator().makeExecutableSchema(typeRegistry, runtimeWiring);
GraphQLSchema newSchema = SchemaTransformer.transformSchema(schema, new GraphQLTypeVisitorStub() {
    @Override
    public TraversalControl visitGraphQLObjectType(GraphQLObjectType node, TraverserContext<GraphQLSchemaElement> context) {
        if (shouldReplace(context)) {
            TreeTransformerUtil.changeNode(context, Scalars.GraphQLString);
        }
        return super.visitGraphQLObjectType(node, context);
    }

    @Override
    public TraversalControl visitBackRef(TraverserContext<GraphQLSchemaElement> context) {
        if (shouldReplace(context)) {
            TreeTransformerUtil.changeNode(context, Scalars.GraphQLString);
        }
        return TraversalControl.CONTINUE;
    }

    private boolean shouldReplace(TraverserContext<GraphQLSchemaElement> context) {
        if (!(context.thisNode() instanceof GraphQLObjectType &&
                ((GraphQLObjectType) context.thisNode()).getName().equals("Foo"))) return false;

        TraverserContext<GraphQLSchemaElement> contextParent = context.getParentContext();
        while (contextParent.thisNode() instanceof GraphQLNonNull ||
                contextParent.thisNode() instanceof GraphQLList) {
            contextParent = contextParent.getParentContext();
        }

        return contextParent.thisNode() instanceof GraphQLFieldDefinition &&
                ((GraphQLFieldDefinition) contextParent.thisNode()).getName().equals("changeMe");
    }
});

Assertions.assertEquals("[Foo]", newSchema.getQueryType().getFieldDefinition("dontChangeMe").getType().toString());
```

**Comment by bbakerman** [comment] 2020-03-29 09:17
Just to explain why this is broken.

The history of GraphlXXX types and equality is a sordid one of legacy.

Nominally they should have full equality / hashcodes  defined since they really are data elements.

However graphql-java originally copied the graphql-js and attached DataFetchers to GraphqlFieldDefinitions and these cant have equality any more like that.

So we relied on object equality and singleton creation of schema element objects.

But as you have found we now have a case where the list / non null wrappers start to reveal this code deficency

Thanks for reporting. And thanks for the reproduction - it made it so much easier to try to reproduce and hopefully fix

**Comment by felipe-gdr** [comment] 2020-04-16 07:10
I could reproduce the same bug (the type of `dontChangeMe` being changed) on a schema that doesn't use `GraphQLList` or `GraphQLNull`.

```
        TypeDefinitionRegistry typeRegistry = new SchemaParser().parse(
                "type Query {\n" +
                        "    changeMe: Foo\n" +
                        "    dontChangeMe: Foo\n" +
                        "}\n" +
                        "\n" +
                        "type Foo {\n" +
                        "    dummy: String\n" +
                        "}\n"
        );
        RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring().build();
        GraphQLSchema schema = new SchemaGenerator().makeExecutableSchema(typeRegistry, runtimeWiring);
        GraphQLSchema newSchema = SchemaTransformer.transformSchema(schema, new GraphQLTypeVisitorStub() {
            @Override
            public TraversalControl visitGraphQLObjectType(GraphQLObjectType node, TraverserContext<GraphQLSchemaElement> context) {
                if (shouldReplace(context)) {
                    TreeTransformerUtil.changeNode(context, Scalars.GraphQLString);
                }
                return super.visitGraphQLObjectType(node, context);
            }

            @Override
            public TraversalControl visitBackRef(TraverserContext<GraphQLSchemaElement> context) {
                if (shouldReplace(context)) {
                    TreeTransformerUtil.changeNode(context, Scalars.GraphQLString);
                }
                return TraversalControl.CONTINUE;
            }

            private boolean shouldReplace(TraverserContext<GraphQLSchemaElement> context) {
                if (!(context.thisNode() instanceof GraphQLObjectType &&
                        ((GraphQLObjectType) context.thisNode()).getName().equals("Foo"))) {
                    return false;
                }

                TraverserContext<GraphQLSchemaElement> contextParent = context.getParentContext();

                return contextParent.thisNode() instanceof GraphQLFieldDefinition &&
                        ((GraphQLFieldDefinition) contextParent.thisNode()).getName().equals("changeMe");
            }
        });

        System.out.println(newSchema.getQueryType().getFieldDefinition("changeMe").getType().toString());
        System.out.println(newSchema.getQueryType().getFieldDefinition("dontChangeMe").getType().toString());
```

Both sysouts print the String scalar type. This makes me think that the bug is caused by something else. I'll continue the investigation.

The point about the implementation of `equals` in `GraphQLNull`/`GraphQLList` is valid though.

**Comment by felipe-gdr** [comment] 2020-04-17 05:35
Ok, I think I got to the bottom of the issue here. Just to reiterate, the behaviour reported is not related to how `GraphQLList` and `GraphQLNonNull` implement equality ;-) 

What was described on the original message is actually expected behaviour. Although not super apparent at first, changing the `Foo` `GraphQLObjectType` to `String` will be applied to all references of type `Foo` in the schema. So calling `TreeTransformerUtil.changeNode(context, Scalars.GraphQLString);`, where `context` is pointing to `Foo`, we'll result in all `Foo` field types being changed to `String`.

In order to achieve what the original message described, which is transforming this schema:
```
        type Query {
            changeMe: Foo 
            dontChangeMe: Foo 
        }
        type Foo {
           bar: String
       } 
```

into this schema:
```
        type Query {
            changeMe: String
            dontChangeMe: Foo 
        }
        type Foo {
           bar: String
       } 
```

we could implement `visitGraphQLFieldDefinition` instead and change the type only for the field we want.

```
        GraphQLSchema newSchema = schemaTransformer.transform(schema, new GraphQLTypeVisitorStub() {
            @Override
            TraversalControl visitGraphQLFieldDefinition(GraphQLFieldDefinition fieldDefinition, TraverserContext<GraphQLSchemaElement> context) {
                if (fieldDefinition.name == "changeMe") {
                    def changedNode = fieldDefinition.transform({ builder -> builder.type(Scalars.GraphQLString) })
                    return changeNode(context, changedNode)
                }
                return TraversalControl.CONTINUE

            }
        })
```

@sachindshinde should that be enough for us to close this issue? 
If you have an example of unexpected behaviour caused by how `GraphQLNonNull` and `GraphQLList` equality is implemented, please post it here so we can look further. Cheers!

**Comment by andimarek** [comment] 2020-05-19 08:13
closing this issue, see last comment.

**Closed by andimarek** 2020-05-19 08:13 UTC
