### ISSUE TITLE
LambdaFetchingSupport causes NoClassDefFoundError when having multiple classloader (OSGi use case)

### ISSUE THREAD

**Issue by LanaLkv** [graphql-java/graphql-java#3113] opened 2023-03-13 10:41 UTC
We run into an issue with graphql.schema.fetching.LambdaFetchingSupport#mkCallFunction when having multiple classloader in our OSGi application.
The 'targetClass' parameter is already loaded with the correct classloader, but later the function call tries to load the class with the classloader of graphql-java, which produces NoClassDefFoundError.

It can also be reproduced in non-OSGi use case with a test that has two class loader:

```
class LambdaFetchingSupportTest extends Specification {
    def "Multiple classloader in LambdaFetchingSupport"() {
        when: "Load class using GroovyShell script in order to get different classloader"
        def shell = new GroovyShell(this.getClass().getClassLoader())
        def result = shell.run(''' package multiple.classloader.test

class MyClass{

    String getName(){
        return "Hello"
    }
}
return new MyClass()
''', "Test.script", [])

        then: "We have two different classloader now"
        result.getClass().getClassLoader() != this.getClass().getClassLoader()

        when:
        def loader1 = this.getClass().getClassLoader()
        def myClass = result.getClass()
        def myClassLoader = myClass.getClassLoader()

        // Loading MyClass with its loader.
        myClassLoader.loadClass(myClass.getName())
        then:
        noExceptionThrown()

        when: "Loading MyClass with another loader"
        loader1.loadClass(myClass.getName())
        then:
        thrown(ClassNotFoundException)

        when: "Also the LambdaFetchingSupport tries to load MyClass with different loader"
        def function = LambdaFetchingSupport.mkCallFunction(myClass, "getName", String.class)
        def expectedRes = function.apply(result)

        then:
        expectedRes == "Hello" // But gets NoClassDefFoundError
    }
}
```

Thank you in advance!

**Comment by bbakerman** [comment] 2023-03-13 20:45
This PR makes the Lambda support more resilient in the face of crossing class loaders

https://github.com/graphql-java/graphql-java/pull/3095

This discussion has more on this

https://github.com/graphql-java/graphql-java/discussions/3100

As a work around you cant turn off the Lambda support JVM wide via `graphql.schema.PropertyDataFetcherHelper#setUseLambdaFactory(false);`

**Comment by bbakerman** [comment] 2023-03-13 20:45
ps... Thank you for the reproduction code

**Comment by bbakerman** [comment] 2023-03-13 21:02
I am going to close this issue as a duplicate of https://github.com/graphql-java/graphql-java/issues/3086

**Closed by bbakerman** 2023-03-13 21:02 UTC
