### ISSUE TITLE
PropertyDataFetcher doesn't find default interface methods

### ISSUE THREAD

**Issue by mrdon-atlassian** [graphql-java/graphql-java#1253] opened 2018-10-01 21:54 UTC
The property data fetcher only looks for methods declared on the class, and not on any interfaces that may supply default methods.  Also, I'm pretty sure super classes aren't searched either.

**Comment by bbakerman** [comment] 2018-10-03 06:08
Your right - it doers not consider default methods on interfaces.  No good reason.  I guess we forgot they can have bodies (it was Java 6.0 code for a long time)

They do search upwards in the class hierarchy however

```
    private Method findPubliclyAccessibleMethod(Class root, String methodName) throws NoSuchMethodException {
        Class currentClass = root;
        while (currentClass != null) {
            String key = mkKey(currentClass, propertyName);
            Method method = METHOD_CACHE.get(key);
            if (method != null) {
                return method;
            }
            if (Modifier.isPublic(currentClass.getModifiers())) {
                method = currentClass.getMethod(methodName);
                if (Modifier.isPublic(method.getModifiers())) {
                    METHOD_CACHE.putIfAbsent(key, method);
                    return method;
                }
            }
            currentClass = currentClass.getSuperclass();
        }
        return root.getMethod(methodName);
    }

```

**Comment by sleberrigaud** [comment] 2018-10-05 06:38
@bbakerman I'm wondering if the default method here was hiding the real root cause for us. I've had another issue yesterday with the same effect and it turned out to be because one of the super class was not visible.

In my case, I had a package-private abstract class with default methods, and different implementations and the method on the abstract class was not found by GraphQL Java.

Maybe I should open a specific issue about that one?

**Comment by sleberrigaud** [comment] 2018-10-24 08:17
Trying to reproduce via a test in `PropertyDataFetcherTest` and can't see to be able to. Wondering if the code to support default interface methods fixed things... 🤷‍♂️

**Comment by bbakerman** [comment] 2018-10-24 10:41
There was no fix - only more tests.  Anyway I will close this

**Closed by bbakerman** 2018-10-24 10:41 UTC
