### ISSUE TITLE
Recursive directive inputs don't work

### ISSUE THREAD

**Issue by enriquedacostacambio** [graphql-java/graphql-java#2290] opened 2021-04-14 00:52 UTC
**Describe the bug**
Directives with recursive inputs fail get instantiated. (Affects `v16.2`)
Example:

```gql
input MyInput {
  a: String
  b: MyInput
}
directive @myDirective(x: MyInput) on FIELD_DEFINITION
type Query {
  f: String @myDirective(x: {b: {a:"yada"}})
}
```

**To Reproduce**
```java
public class Test {
    public static void main(String[] args) {
        String sdl =
          "input MyInput {\n" +
          "  a: String\n" +
          "  b: MyInput\n" +
          "}\n" +
          "directive @myDirective(x: MyInput) on FIELD_DEFINITION\n" +
          "type Query {\n" +
          "  f: String @myDirective(x: {b: {a:\"yada\"}})\n" +
          "}\n";
        TypeDefinitionRegistry registry = new SchemaParser().parse(sdl);
        UnExecutableSchemaGenerator.makeUnExecutableSchema(registry);
    }
```

**Stacktrace**
```
Exception in thread "main" graphql.AssertException: Internal error: should never happen: cannot build value of type MyInput from object class ObjectValue with instance ObjectValue{objectFields=[ObjectField{name='a', value=StringValue{value='yada'}}]}
	at graphql.Assert.assertShouldNeverHappen(Assert.java:53)
	at graphql.schema.idl.SchemaGeneratorHelper.buildValue(SchemaGeneratorHelper.java:282)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildObjectValue$1(SchemaGeneratorHelper.java:303)
	at graphql.com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at graphql.schema.idl.SchemaGeneratorHelper.buildObjectValue(SchemaGeneratorHelper.java:300)
	at graphql.schema.idl.SchemaGeneratorHelper.buildValue(SchemaGeneratorHelper.java:280)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveArgument(SchemaGeneratorHelper.java:403)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildDirective$9(SchemaGeneratorHelper.java:384)
	at graphql.collect.ImmutableKit.map(ImmutableKit.java:83)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirective(SchemaGeneratorHelper.java:384)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirective(SchemaGeneratorHelper.java:355)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectives(SchemaGeneratorHelper.java:731)
	at graphql.schema.idl.SchemaGeneratorHelper.buildField(SchemaGeneratorHelper.java:980)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildObjectType$32(SchemaGeneratorHelper.java:834)
	at graphql.com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at graphql.schema.idl.SchemaGeneratorHelper.buildObjectType(SchemaGeneratorHelper.java:833)
	at graphql.schema.idl.SchemaGeneratorHelper.buildOutputType(SchemaGeneratorHelper.java:953)
	at graphql.schema.idl.SchemaGeneratorHelper.buildOperations(SchemaGeneratorHelper.java:1088)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchemaImpl(SchemaGenerator.java:92)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:79)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:52)
	at graphql.schema.idl.UnExecutableSchemaGenerator.makeUnExecutableSchema(UnExecutableSchemaGenerator.java:28)
	at com.credify.graphql.schema.transform.TransformerTestUtils.main(TransformerTestUtils.java:39)
```

**Potential solution**
The issue is that the `requiredType` is a `GraphQLTypeReference`, it could be resolved by name from the `BuildContext.inputGTypes` map.

**Comment by Andy2003** [comment] 2021-04-15 15:28
duplicate of #2238

**Comment by bbakerman** [comment] 2021-07-04 08:15
See https://github.com/graphql-java/graphql-java/pull/2422 - this shows it is working on latest master - I am not sure when  this got fixed but it works on master now

**Closed by bbakerman** 2021-07-04 08:15 UTC
