### ISSUE TITLE
Example usage of datafetcherfactory

### ISSUE THREAD

**Issue by babadofar** [graphql-java/graphql-java#910] opened 2018-02-06 08:20 UTC
I'm using GraphQL with Spring boot, and have a GraphQLObjectType with an injected repository which is used in the datafetcher. Naturally, this makes the GraphQlObjectType not static, which breaks unit tests. (might be a separate issue, actually).
Using a datafetcherfactory might be a solution, but I'm not quite sure how to do it. Will there be any documentation/examples out soon?

**Comment by bbakerman** [comment] 2018-02-07 08:06
Are you building your GraphQLObjectType fields by hand or by schema file or some other mechanism.

Basically a GraphQLFieldDefinition contains the data fetcher factory to use when getting a value from that field

By hand you use the GraphQLFieldDefinition builder

If you are using Schema generation then a WiringFactory allows to it be specified

See `graphql.schema.idl.WiringFactory#getDataFetcherFactory`

if you are using annotation magic from some other library build on top of graphql-java then I dont know how they allow you to do it.

**Comment by babadofar** [comment] 2018-02-07 15:21
I'm building the GraphQLObjectType  by hand, not using IDL schemas. 
No annotation magic, just plain simple code.  So what I'm curious about is how to use Data Fetcher Factory with GraphQLFieldDefinition

**Comment by bbakerman** [comment] 2018-02-10 09:15
When used with a GraphQLFieldDefinition it is simply and indirection for getDataFetcher.

That is instead of  getting the data fetcher directly, it calls a factory and hence you can swap in implementations between calls if you need it.

or you could it to use Spring ApplicationContext to get the fully wired bean that is the data fetcher say.  Think of it how BeanFactories work in Spring... but for data fetchers


The basic ones have a data fetcher factory that delegates immediately to the standard Field / PropertyDataFetchers. 

            public GraphQLFieldDefinition build() {
            if (dataFetcherFactory == null) {
                if (isField) {
                    dataFetcherFactory = DataFetcherFactories.useDataFetcher(new FieldDataFetcher<>(name));
                } else {
                    dataFetcherFactory = DataFetcherFactories.useDataFetcher(new PropertyDataFetcher<>(name));
                }
            }
            return new GraphQLFieldDefinition(name, description, type, dataFetcherFactory, arguments, deprecationReason, directives, definition);
        }

**Comment by bbakerman** [comment] 2018-02-11 07:32
I am going to close this issue because its not a bug and I think its been explained

**Closed by bbakerman** 2018-02-11 07:32 UTC

**Comment by asfernandes** [comment] 2019-04-12 17:52
In relation to this question, I do want to understand how to use a DataFetcherFactory with a injected `@AutoWire` field when building the `GraphQLFieldDefinition`.
