### ISSUE TITLE
parseLiteral not called for custom GraphQLScalarType when input passed as variable

### ISSUE THREAD

**Issue by fibbers** [graphql-java/graphql-java#220] opened 2016-10-07 11:39 UTC
I have a custom GraphQLScalarType defined to parse and display joda `Duration` objects:

```java
	public static GraphQLScalarType Duration = new GraphQLScalarType("Duration", "A time-duration expressed in ms", new Coercing() {
		public Long serialize(Object input) {
			return ((Duration) input).getMillis();
		}
		
		public org.joda.time.Duration parseValue(Object input) {
			// Expected: Duration-object from #parseLiteral below.
			// However, when input passed via variables, this is an Integer instead
			return (org.joda.time.Duration) input;
		}
		
		@Override
		public org.joda.time.Duration parseLiteral(Object astInput) {
			// Only called when input is directly passed in GraphQL.
			// Never called when input is given via variable
			...
			return (Duration) value;
		}
	});
```

When I send this mutation query (where "`duration`"-field is declared as `Duration` type):

```graphql
mutation DoSomethingWithDuration($input: DurationInput!){
  blabla(input:$input) {
    ...
  }
}

variables:
{
  "input": {
    "duration": 0
  }
}
```

`parseLiteral` is not called on my custom type, so my code breaks because `parseValue` gets an `Integer` instead of a `Duration`.

When I send this mutation query:

```graphql
mutation  {
  blabla(input: {duration: 0}) {
    ...
  }
}
```

the coercing happens as expected and `parseLiteral` is executed.

I'm using a workaround to also handle Integers inside `parseValue`, but I think passing input as a variable or passing it hardcoded should be handled the same way.

Any ideas about this?

NB: I'm using version `2016-09-21T06-38-24`

**Comment by dminkovsky** [comment] 2016-10-24 16:40
Hey thanks for posting. I procrastinated responding to this when I first read it, thinking it would require more investigation. But actually it seems simple enough...

In summary, I think the problem is that your `parseValue`/`parseLiteral` methods aren't actually doing any parsing! They're just casting. And I'm not sure why it's working at all... 

In both `parseValue` and `parseLiteral` you need to actually create the `Duration` you want from the input object. There's no reason why `Object` would actually be a `Duration` already, especially in `parseLiteral`, where `Object` would be an instance of `IntValue` if the input is `0`. In `parseValue` you could already have a `Duration` for `input.duration` if you passed a `Duration` as input in the `Map<String,Object`> you provided as args to `GraphQL.execute()`. But anyway, you can't just cast, you need to "parse".

---

> When I send this mutation query ... parseLiteral is not called on my custom type

Because in this case you are passing the variable as a variable reference, not a literal value in the query.

---

> But I am not sure why this would work:

This should not work... I am not sure why any of it is working :).

**Comment by dminkovsky** [comment] 2016-10-26 16:12
Going to close this for now, since I think it's not a big. Please reopen if otherwise.

**Closed by dminkovsky** 2016-10-26 16:12 UTC
