### ISSUE TITLE
Failed validation for alias clashing with another field

### ISSUE THREAD

**Issue by martinbonnin** [graphql-java/graphql-java#3332] opened 2023-09-18 13:02 UTC
The following test fails:

```kotlin
    @Test
    fun test() {
        val schemaString = """
            type Query {
                cat: Cat!
            }
            
            type Cat {
                foo1: String!
                foo2: String!
            }
        """.trimIndent()

        val documentString = """
            query GetCat {
              cat {
                foo1
                foo1: foo2
              }
            }

        """.trimIndent()
        val typeDefinitionRegistry = SchemaParser().parse(schemaString)
        val document = Parser().parseDocument(documentString)
        val graphQLSchema = SchemaGenerator().makeExecutableSchema(typeDefinitionRegistry, RuntimeWiring.newRuntimeWiring().build())
        val result = Validator().validateDocument(graphQLSchema, document, Locale.US)

        // There should be a validation error at this point.
        check(result.isNotEmpty())
    }
```

I would expect a validation error because `foo1` and `foo1: foo2` cannot be merged.

Edit: this is on version `21.1`

**Comment by bbakerman** [comment] 2023-09-21 06:33
I would expect this to be the case as well

**Comment by bbakerman** [comment] 2023-09-21 07:48
https://spec.graphql.org/June2018/#sec-Field-Selection-Merging says as much

**Comment by bbakerman** [comment] 2023-09-21 08:22
`graphql.validation.rules.OverlappingFieldsCanBeMergedTest#Alias masking direct field access` seems to have test for this

```
fragment aliasMaskingDirectFieldAccess on Dog {
            name: nickname
            name
        }
        ```

but maybe there is a fragement specific bit of code.  Checking now...

**Comment by bbakerman** [comment] 2023-09-21 08:58
I made a reproduction PR : https://github.com/graphql-java/graphql-java/pull/3334

Its failing BUT I have another case that is passing.  Curious - I haven't debugged it further but this one looks like a curly one

**Comment by bbakerman** [comment] 2023-09-21 11:23
More observations as I test (and so I dont lose them)

```
        { dog {
            name: nickname
            name
        }}
```

This ordering passes the test and kit produces errors as expected .  However

```
        { dog {
            name
            name: nickname
        }}

```

does not pass the test and it produces NO validation errors as reported above.

It seems the ordering of the alias is confusing the validation code.  Not sure what because I haven't got that far

**Comment by bbakerman** [comment] 2023-09-21 14:01
I think I found the problem - we failed to use unwrapped parent types in the code.  The earlier idea that it was ordering if aliases was a red herring.

But in the existing tests we have a simple type `dog : Dog` while the provided example above is `cat : Cat!` - that is its a modified nonnull type wrapping a `Cat` type.

The code failed to store the unwrapped part when it associates it per field per parent type.  Then later it does compositions on what it expects to be unwrapped and it does match and hence it thinks it's ok.

This has been like this since maybe Aug 2021 based on git history... maybe even longer.

To hit this you need to have a "clashing field name / field alias" AND it needed to be inside a modified type (eg non null or list)

**Comment by martinbonnin** [comment] 2023-09-21 14:20
I'm relived that GraphQL isn't biased for 🐶 over 🐱 :). Thanks for the thorough investigation!

**Comment by dondonz** [comment] 2023-10-17 04:29
Fixed by https://github.com/graphql-java/graphql-java/pull/3334

**Closed by dondonz** 2023-10-17 04:29 UTC
