### ISSUE TITLE
graphql.schema.GraphQLList v3.0.0

### ISSUE THREAD

**Issue by MartinX3** [graphql-java/graphql-java#715] opened 2017-09-16 14:57 UTC
GraphQL v3.0.0 because of
```xml
<!--GraphQL Spring boot starter-->
        <dependency>
            <groupId>com.merapar</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>1.0.2</version>
        </dependency>
```

graphql.schema.GraphQLList hates the Dependency Injection of Spring Boot.

There are two fields which owns each other, but they can't be build, because of

```java
 public GraphQLList(GraphQLType wrappedType) {
        assertNotNull(wrappedType, "wrappedType can't be null");
        this.wrappedType = wrappedType;
    }
```

But it's fine, that wrappedType is NULL that this point, because it will be injected later, via the @PostConstructor.
By the way, I'm using dependency injector setters
```java
    @Autowired
    public void setOrderFields(OrderFields orderFields) {
        this.orderFields = orderFields;
    }
```

**Comment by andimarek** [comment] 2017-09-16 15:12
Hi @MartinX3,

I am not really sure what this issue is about: do you want us to change `GraphQLList`? This will not happen, because `GraphQLList` is designed to be immutable. 

Maybe this issue should be addressed in the `graphql-spring-boot-starter` project.

**Comment by bbakerman** [comment] 2017-09-17 04:38
GraphqlList is not designed to be a singleton component aka like most "code components" in Spring.  Its a wrapper class for indicate that a graphql Type X is non null.

If you want a factory of types then I suggest you use Spring factories to create your types rather than Autowiring

**Comment by bbakerman** [comment] 2017-09-17 04:45
I am going to close this issue because graphql-java is working as designed and you can work around this in Spring

**Closed by bbakerman** 2017-09-17 04:45 UTC
