### ISSUE TITLE
graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLObjectType

### ISSUE THREAD

**Issue by ckersters** [graphql-java/graphql-java#2087] opened 2020-10-30 10:32 UTC
Hello,

**Describe the bug**
Using either releases 15.0 or .14.0 (from graphql java servlet 10.0 or 9.3), when I execute schemaGenerator.makeExecutableSchema, I get this exception
(Release 15.0)
java.lang.ClassCastException: graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLObjectType
	graphql.schema.idl.SchemaGenerator.lambda$buildUnionType$19(SchemaGenerator.java:629)
	java.util.ArrayList.forEach(ArrayList.java:1249)
	graphql.schema.idl.SchemaGenerator.buildUnionType(SchemaGenerator.java:624)
	graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:438)
	graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:784)
	graphql.schema.idl.SchemaGenerator.lambda$buildObjectType$5(SchemaGenerator.java:501)
	java.util.ArrayList.forEach(ArrayList.java:1249)
	graphql.schema.idl.SchemaGenerator.buildObjectType(SchemaGenerator.java:500)
	graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:434)
        [...]
(detailed in attachment)

(Release 14.0)
java.lang.ClassCastException: graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLObjectType
	graphql.schema.idl.SchemaGenerator.lambda$buildUnionType$13(SchemaGenerator.java:598)
	java.util.ArrayList.forEach(ArrayList.java:1249)
	graphql.schema.idl.SchemaGenerator.buildUnionType(SchemaGenerator.java:593)
	graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:439)
	graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:737)
	graphql.schema.idl.SchemaGenerator.lambda$buildObjectType$3(SchemaGenerator.java:502)
	java.util.ArrayList.forEach(ArrayList.java:1249)
	graphql.schema.idl.SchemaGenerator.buildObjectType(SchemaGenerator.java:501)
	graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:435)
        [...]

**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.
It looks like the problem comes from some form or recursion in unions. My schema (SDL) contains the following (see full schema in attachment):
type PARAL implements Object & NamedObject {
	name: String!
	id: Int!
	[...]
	CLOSBY: CLOSR!
}
type CLOSR implements Object & NamedObject {
	name: String!
	id: Int!
	[...]
	CLOSES: CNTRL!
}

union CNTRL = SELEC | PARAL

Problem happens in SchemaGenerator.buildUnionType, when processing
            if (outputType instanceof GraphQLTypeReference) {
                builder.possibleType((GraphQLTypeReference) outputType);
            } else {
                builder.possibleType((GraphQLObjectType) outputType);
            }
as the output type is a GraphQLUnionType.

Thanks
[stacktrace.txt](https://github.com/graphql-java/graphql-java/files/5464497/stacktrace.txt)
[graphqls.txt](https://github.com/graphql-java/graphql-java/files/5464501/graphqls.txt)

**Comment by nutharsh** [comment] 2020-11-02 18:33
I was able to successfully reproduce this issue on v15.0 version.

Here is the sample source code I wrote to get to this - 
**Main class with default type resolver**: [Issue2087.java](https://github.com/nutharsh/graphql-java-100days/blob/master/src/main/java/com/adarsh/graphql/java/issue2087/Issue2087.java)
**GraphQL schema file**: [issue2087.graphqls](https://github.com/nutharsh/graphql-java-100days/blob/master/src/main/resources/issue2087.graphqls)

One key thing which was missing in steps to reproduce was the default type resolver for _153_ interface/union types. Once I registered that via `RuntimeWiring` instance, calling `makeExecutableSchema()` throws above error.

**Comment by nutharsh** [comment] 2020-11-03 12:09
@bbakerman @andimarek -  Help me in confirming that this is **_not_** an issue as per GraphQL spec.

IMHO, this shouldn't be an issue with the library But error message is not something readily interpretable.

Here is the extract I have taken from above provided full schema definition.

```
union PDDSYSDF = CLOSR | CNTRL | EXTRNUS | JUNCTION | STOREUSP
union CNTRL = SELEC | PARAL
```

Here `SELEC, PARAL, CLOSR, JUNCTION` are the only Object base types.

**_We are getting the issue when library makes an attempts to resolve  Union type PDDSYSDF and encounters Union type CNTRL which was supposed to be Object base type._**

GraphQL spec under `Type Validation in Union type` tells me that 
```
The member types of a Union type must all be Object base types; 
Scalar, Interface and Union types must not be member types of a Union.
Similarly, wrapping types must not be member types of a Union.
```
Reference: http://spec.graphql.org/draft/#sec-Unions

Clearly, in the above supplied sample schema we could see that `Union ` type `PDDSYSDF `is trying to define `CNTRL ` as possible member type which happens to be `Union` type in itself _which is not valid as per the spec_.

But the stack trace we get during makeExecutableSchema() is hinting us that It is expecting/assuming as per spec that all possible member types are Object base types. But, it is not clear enough to say that UNION must not have UNION / Scalar / Interface as member types. May be we need to add that logic to fail with proper error message.

**Comment by andimarek** [comment] 2020-11-03 21:58
@nutharsh I agree that this is not really a problem, because as you said: a Union can only consist of Objects.

SchemaTransformer is pretty "raw": it lets you change the Schema in an arbitrary way including invalid states.

**Comment by bbakerman** [comment] 2020-11-04 22:11
I am a bit puzzled here.  The pre-generation SDL code has checks that a union type is ALL object types

`graphql.schema.idl.UnionTypesChecker#checkUnionType(graphql.schema.idl.TypeDefinitionRegistry, graphql.language.UnionTypeDefinition, java.util.List<graphql.GraphQLError>)`

```
            if (!memberTypeDefinition.isPresent() || !(memberTypeDefinition.get() instanceof ObjectTypeDefinition)) {
                errors.add(new UnionTypeError(unionTypeDefinition, format("The member types of a Union type must all be Object base types. member type '%s' in Union '%s' is invalid.", ((TypeName) memberType).getName(), unionTypeDefinition.getName())));
                continue;
            }
```

how is the schema generator being called such that the first phase "SDL type checking" is NOT being called.

This code is intended to catch exactly what is being described here.  Hmmm I wonder how its not being called.


Ahhh just checked - this union checking code was added AFTER 15.0 was released.

https://github.com/graphql-java/graphql-java/pull/1967

So ongoing this will not be a problem

**Comment by bbakerman** [comment] 2020-11-04 22:13
I am going to close this issue because it has been fixed and we have tests for this case

**Closed by bbakerman** 2020-11-04 22:13 UTC
