### ISSUE TITLE
Issue with the introspection query in current version of library

### ISSUE THREAD

**Issue by yaakov123** [graphql-java/graphql-java#2608] opened 2021-11-11 14:26 UTC
**Describe the bug**
It seems that there's an issue with the introspection query that located at:

https://github.com/graphql-java/graphql-java/blob/v17.0/src/main/java/graphql/introspection/IntrospectionQuery.java
I attempted to run that query against a GraphiQL interface and there were a bunch of syntax issues. This issue does not occur in a previous version of the library:

https://github.com/graphql-java/graphql-java/blob/v15.0/src/main/java/graphql/introspection/IntrospectionQuery.java

**Comment by bbakerman** [comment] 2021-11-12 05:37
This is currently defined as the following and has not changed since 2016

```graphql

  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
        isRepeatable
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields(includeDeprecated: true) {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
    isDeprecated
    deprecationReason
  }

fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
```

I just run it in a server running GraphiQL and the latest graphql -java and it works.  I am pretty sure it works but not software is perfect.

Could you list the syntax errors you are getting to help debug this.

**Comment by yaakov123** [comment] 2021-11-14 10:34
If you put that query here: https://lucasconstantino.github.io/graphiql-online/ you should see the relevant syntax errors.

Also, you can  see that the file changed between v15 and v17 in the links I sent in the original issue.

**Comment by jord1e** [comment] 2021-11-14 23:21
That GraphiQL instance is pointing to https://countries.trevorblades.com/

If you look up the `package.json` used by the endpoint you will notice `graphql`-js is on version `^14.6.0`:
https://github.com/trevorblades/countries/blob/628067a7b36f588575ba10d64b0f8c7d767d36fa/package.json#L13

Support for deprecated fields for `inputFields(includeDeprecated: true)` [was only added in `16.0.0`](https://github.com/graphql/graphql-js/commit/8261922bafb8c2b5c5041093ce271bdfcdf133c3).

The feature also hasn't yet been added to the spec yet: https://github.com/graphql/graphql-spec/pull/805 (I don't know how that it supposed to work on the `graphql-java` side?)

There is not much wrong with graphql-java, trevorblades need to update their package from `14.7.0` (which [was released on 2020-07-06](https://github.com/graphql/graphql-js/releases/tag/v14.7.0) (!!!)) to the latest version.

**Comment by bbakerman** [comment] 2021-11-15 06:09
Thanks @jord1e for explaining the problem.  I will close this issue as there is not a bug in graphql-java

**Closed by bbakerman** 2021-11-15 06:09 UTC
