### ISSUE TITLE
Reference Equality Check in VariableTypesMatchRule breaks if GraphQLInputObjectType is created multiple times.

### ISSUE THREAD

**Issue by davidscottcohen** [graphql-java/graphql-java#85] opened 2016-02-11 01:52 UTC
Normally in schema creation, it is OK to create multiple instances of the same type object.  However, `VariableTypesMatchRule` uses reference equality, so if I create my schema with multiple instances of an equivalent `GraphQLObjectInputType` then I will get validation failures.  This was tricky to track down because I create input types in methods (e.g. `private GraphQLInputObjectType  createPropertyMatchType()`) and then call those methods when I need it them.

I think the ideal solution is to use deep equality instead of reference equality in `VariableTypeMatchRule`.

Otherwise some process in schema creation should canonicalize the types within the schema.

**Comment by yrashk** [comment] 2016-05-04 07:49
I think I ran into a similar case with fragments (`PossibleFragmentSpreads`), particularly this https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/validation/rules/PossibleFragmentSpreads.java#L76 makes use of reference equality.

**Comment by yrashk** [comment] 2016-05-06 06:29
@andimarek @alexkrebiehl @danielkwinsor

I want to discuss this issue. I believe it is important to make GraphQL type information equality testing deep as I can't see where reference equality testing is more useful (prove me wrong?).

Would it be sufficient to limit deep equality to names (as the names can't clash) or should we do full deep equality? For a quick fix, name equality works. What do you think?

**Comment by andimarek** [comment] 2016-05-06 06:47
The graphql schema was designed to be based on the principle that for each type there is exactly one Java Instance representing this type. That's the reason the ckecks are using reference equality. This is just simpler.

Of course we could change that, but I am not sure about the overall consequences.

**Comment by yrashk** [comment] 2016-05-06 07:00
Andreas, totally agree that this is simpler. However, I have a case where
it is actually the opposite. In graphql-java-annotations I don't know all
of the upcoming schema ahead of the time (it's being processed piece by
piece, particularly important for dynamic schema composition I do with
OSGi) and it's becoming a non-trivial problem, so right now my workaround
is to subclass graphql classes to implement deeper type checks to avoid
checking by reference. I am not sure what would we lose if we were to ditch
reference equality in favour of deeper equality, any thoughts?


Also, if you were to do the deeper equality check, how would you answer the
question in my previous comment?

On Fri, May 6, 2016 at 12:47 AM, Andreas Marek <notifications@github.com>
wrote:

> The graphql schema was designed to be based on the principle that for each
> type there is exactly one Java Instance representing this type. That's the
> reason the ckecks are using reference equality. This is just simpler.
>
> Of course we could change that, but I am not sure about the overall
> consequences.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/graphql-java/graphql-java/issues/85#issuecomment-217361404>
>



-- 
Y.

**Comment by andimarek** [comment] 2016-05-06 07:06
@yrashk Not sure about how to implement it best: Of course just checking names is enough, but I fear unclear side-effects or bugs, when it is not fully checked. Therefore I would say it should be a real deep equal check.

**Comment by yrashk** [comment] 2016-05-06 07:10
Can you give me an idea of a potential side-effect or a bug? I understand your motivations, but I'd rather avoid defensive programming if you know what I mean.

We have to lay it out like that: if you do end up having multiple types with the same name, one of the variations of it will ultimately win during schema composition, correct? What if we specify and document *how* the winner is chosen?

**Comment by andimarek** [comment] 2016-05-06 07:41
I was just thinking: You have a two different objects with the same name but different properties: And object 1 is used for validation and object 2 is used for executing. This is very unfortunate and we should try to avoid such a scenario.

**Comment by yrashk** [comment] 2016-05-06 14:35
If two instances are used for different purposes yet bear the same name, should it matter, though?

**Comment by danielkwinsor** [comment] 2016-05-06 15:54
In graphql-java-type-generator we will take a *.class and create an object using some generated name.  There are a few problems here, but one is that you can have multiple java classes with the same name in different class loaders.  I consider this to be a problem of g-j-t-g, but there are so many other examples that might not be.

Authorization: I'm going to do per field authorization using a fetcher that optionally returns null, but someone else might want to have 2 different AccountTypes, 1 for customer, another for customer service.  In that case, makes sense to resolve based upon a Type Dictionary given to the schema -- but this is not a full solution in edge cases like the Type Dictionary containing multiple types same name.

Last, I am thinking about duck typing, and it sounds like a per-field-name check would allow for duck typing.  Suppose we recursively do a comparison and see that all fields of 2 AccountTypes are equal in name.  Then duck typing says they are equal.  But what if DataFetcher is vastly different... are these equivalent types or not?

**Comment by yrashk** [comment] 2016-05-06 16:07
Since DataFetcher wouldn't modify the interface, though should not be considered different types. All that matters (IMO) is the shape of the interface. 

The reason why I suggested using just the name as an equality test is simply because we can't have multiple types with the same name. That said, verifying the structure (fields and field types) is also a reasonable approach.

**Comment by danielkwinsor** [comment] 2016-05-06 16:28
Right, if we start worrying about DataFetcher equality we are in for a world of hurt.

Your second statement is true in GraphQL, that GraphQL cannot have multiple types same name, but for java it is possible.  If java types have overlapping FQNs, but different structure, what should I name a GraphQLObjectType based upon those java types?  I would feel safer with a deep field name/type check, and then our 2 AccountTypes are either equal or not, but both are permitted to exist simultaneously.

**Comment by danielkwinsor** [comment] 2016-05-06 16:33
To clarify the last statement, that would mean we are taking the approach that is potentially against http://facebook.github.io/graphql/#sec-Type-System if the 2 AccountType GraphQLObjectTypes fail the equality check.

If we did that, we'd need another layer of check that only allows for 1 type, like the Type Dictionary or something.

**Comment by yrashk** [comment] 2016-05-06 16:49
I am fine with deeper equality (shape testing for the sake of catching weird issues), but I think we should adhere to one type one name principle. In graphql-java-annotation I solve this by having `@GraphQLName` annotation that can override type names.

In your case, my suggestion would be to generate different names for classes with the same name in different packages. That seems to be a better approach in terms of spec adherence. Thoughts?

**Comment by danielkwinsor** [comment] 2016-05-06 17:34
In terms of my graphql-java-type-generator, it stores types with key == type name, so there cannot be duplicate GraphQL types.  Further, the default type name is the FQN with underscores, also with the ability to override the name.  (But actually I did realize something I could do better).

So actually I am thinking in the more general case.  What is to stop a user from hand coding 2 AccountTypes, which then may or may not be equal if we make an equality change?

**Comment by yrashk** [comment] 2016-05-06 17:36
Nothing is stopping them to do so. What we can do is to refuse adding two
unequal types with the same name to the schema, proactively, so this type
of mistake can be caught early.

On Friday, 6 May 2016, danielkwinsor <notifications@github.com> wrote:

> In terms of my graphql-java-type-generator, it stores types with key ==
> type name, so there cannot be duplicate GraphQL types. Further, the default
> type name is the FQN with underscores, also with the ability to override
> the name. (But actually I did realize something I could do better).
>
> So actually I am thinking in the more general case. What is to stop a user
> from hand coding 2 AccountTypes, which then may or may not be equal if we
> make an equality change?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/graphql-java/graphql-java/issues/85#issuecomment-217508577>
>


-- 
Y.

**Comment by metacosm** [comment] 2016-10-15 00:51
I would argue for type uniqueness based on name as well: one name <-> one type. This seems like a reasonable assumption which doesn't constrain the model too much and allows for very simple equals and hashCode implementations.

**Comment by dminkovsky** [comment] 2016-10-19 15:22
Let's talk more about this. I don't have a ton of Java experience, especially in terms of seeing how Java libraries in practice practically solve such problems. 

I really like the idea of moving the schema definition types in the direction of [value-based classes](http://docs.oracle.com/javase/8/docs/api/java/lang/doc-files/ValueBased.html). However, I don't see exactly how a single string property like "name" is actually any sort of meaningful equivalence relation. 

Then again, I also see what @danielkwinsor means when [he says](https://github.com/graphql-java/graphql-java/issues/85#issuecomment-217490932):

> if we start worrying about DataFetcher equality we are in for a world of hurt.

Which is fine: for a field definition we don't have to look at data fetchers. And we shouldn't, because we want a field defined on an interface (does not have a fetcher) and a field defined on an object (has a fetcher) to possibly be equivalent, data fetcher aside.

But say we have two object types. How can we just compare their names and skip looking at their fields?

Finally, circularity is also an issue. Types can be circular: a field on an object type can be of that same type. So, what: we ignore type in equality? Seems like a poor equivalence relation for an object/interface if you ignore its fields and their type.

**Comment by metacosm** [comment] 2016-10-20 20:11
The specification states:
> All types within a GraphQL schema must have unique names. No two provided types may have the same name. No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).

From this, I infer that two types with the same name *must* be equal or the schema is invalid. Considering a type's name should therefore be enough to ensure its identity which is all that matters for equals and hashCode (and more importantly, how the JDK uses them).

**Comment by dminkovsky** [comment] 2016-10-20 21:55
> From this, I infer that two types with the same name must be equal or the schema is invalid.

Right: they _must_ be equal according to the spec. But what if due to say, a bug, they are not? 

Say I have one spot in my code where I have:

```
newObject
  .name("Obj")
  .field(newFieldDefinition()
    .name("field")
    .type(GraphQLString)
    .build())
  .build()
```

and another where:


```
newObject
  .name("Obj")
  .field(newFieldDefinition()
    .name("field")
    .type(GraphQLInt)
    .build())
  .build()
```

then, say, in some other code I compare these definitions and the result is they are equivalent. Then how much longer down the line will this bug manifest? 

My point is—and sorry truly if I am missing something or am just being too pedantic—that yes, the spec says a type's name should be unique. But from a runtime Java perspective, two object definitions with the same name can be totally different, and the usefulness of an equivalence relation that only compares their names seems, well, not useful, and even worse, bug prone?

**Comment by metacosm** [comment] 2016-10-21 07:35
The error would be detected when the schema is built (at I'd assume): an error should be thrown as soon as a new type is being added with an already registered name is added. At least, that's my understanding but I am far from having the big picture on this :)

**Comment by metacosm** [comment] 2016-10-21 08:15
One last point :)

>  But from a runtime Java perspective, two object definitions with the same name can be totally different, and the usefulness of an equivalence relation that only compares their names seems, well, not useful, and even worse, bug prone?

The reverse from a Java perspective is just as bad. It breaks pretty much all the Collections that semantically equal objects are considered different because they lack proper equals / hashCode implementations. A good reference on that point: http://www.ibm.com/developerworks/library/j-jtp05273/

**Comment by dminkovsky** [comment] 2016-10-24 15:58
> The error would be detected when the schema is built [...]

Not if it's a type that's not included in a schema. It sounds like you're doing just that in a type resolver: returning a type by building it right then and there. If it's never part of a schema, there's no way to validate it against other types.

>  If we cannot provide a valid implementation of these methods that allows semantically equivalent objects to be recognized as equal, then we shouldn't allow direct instantiation of these types and always go through the schema as a factory/registry.

Yes, I agree... that's why, for example, I liked the idea that type resolvers should have access to the schema. But it would be better to figure out a way to have equals/hashCode... I think. My problem is that I spent like 4-5 hours on it one day and couldn't quite find a good way that works with all the aforementioned issues, like type circularity or data fetcher equivalence. I would love to have these classes be value-based, as long as the equivalence is meaningful.

> The reverse from a Java perspective is just as bad. It breaks pretty much all the Collections that semantically equal objects are considered different because they lack proper equals / hashCode implementations.

Yeah, I agree. I want to hear what other people have to in order to decide how to move forward. Right now we have three options:

1. Keeping things as they are: you can construct definition types however you please, but we aware they only support reference equality.
2. Definition types can be constructed only within the scope of a schema and can only be accessed from that schema.
3. Definition types can be constructed ad-hoc but support equality/hashCode.

**Comment by metacosm** [comment] 2016-10-24 16:10
>The error would be detected when the schema is built [...]
Not if it's a type that's not included in a schema. It sounds like you're doing just that in a type resolver: returning a type by building it right then and there. If it's never part of a schema, there's no way to validate it against other types.

Yes, I missed that part initially. :)

Regarding the possible options, the easiest one in term of modifying existing client code would be providing *sensible* equals/hashCode implementations (for some value of "sensible"). Going through the schema would require significant re-write of the code I think, as well as change how you can use the API. I started looking into it (not too long) and I could already issues with the graphql-java-servlet project since we would need to get access to the schema from the query / mutation providers in order to create the needed types. On the other hand, the project I currently work on would definitely benefit from incremental updates of the schema (as GraphQL types could be generated on the fly based on OSGi bundle events and right now the only option I have is to redeploy my provider on each such event and re-generate the whole schema when a simple use case already has hundreds of types) so I might need to fork / implement an alternative to the current solution anyway. 
Solution 1 is unacceptable for me completely break my application since I would require access to the schema to be able to retrieve the proper type instance when I resolve it, which I can't because I don't have access to the schema at the moment (due to the architecture of graphql-java-servlet).

**Comment by dminkovsky** [comment] 2016-10-24 16:18
Thanks for this. I'll think about it a bit more. Also reading the link, which is very interesting considering it has a heading called "What should equality mean?" and it's by BG :D

**Comment by andimarek** [comment] 2017-04-08 14:12
I would like to tacke this issue, either by closing or implementing some kind of equally check:

Thinking about the java classes involved I see one major problem: the data fetcher. This is a class which is only equal by reference ... nothing else makes sense, because it logic.

This means that a `GraphQLFieldDefinition` can't have any deep equal check and should probably not have a name equals check either because of the data fetcher. 
This is somehow unfortunate I must say and I am not really happy with it.

**Comment by andimarek** [comment] 2017-05-20 02:49
closing it, because we will not implement equals/hashcode for Types, because they contain `DataFetcher` and `TypeResolver`.

**Closed by andimarek** 2017-05-20 02:49 UTC
