### ISSUE TITLE
Extensions are not rendered from GraphQLError that originated from CompletableFuture

### ISSUE THREAD

**Issue by thestarmaker** [graphql-java/graphql-java#1018] opened 2018-04-16 17:27 UTC
Hi there, 

I have noticed that if a DataFetcher returns a CompletableFuture, and this CompletableFuture completes exceptionally with GraphQLError as an exception, then the extensions on this GraphQLError are nor rendered to the response. 

The reason is that ExecutionStrategy.handleFetchingExcetion() just delegates to 

`parameters.deferredErrorSupport().onFetchingException(parameters, e);`

and it is never checked that the supplied Throwable may implement GraphQLError. This means that the async code can not append any custom extensions to the errors.

This happens in graphql-java 8.0

**Comment by bbakerman** [comment] 2018-05-09 23:37
I am not seeing this behaviour for extensions.

I have written a new test that shows it working (see #1037 )

Can you expand on this problem more or perhaps do a unit test that demonstrates it happening.

graphql.ExceptionWhileDataFetching#ExceptionWhileDataFetching is the class in question that transfers exceptions that are GraphqlErrors

**Comment by bbakerman** [comment] 2018-05-20 09:41
I am going to close this because I believe its working as expected

**Comment by jaredculp** [comment] 2021-07-29 15:17
The test referenced doesn't use a data fetcher that returns a CompletableFuture.

**Comment by bbakerman** [comment] 2021-07-30 12:43
Do you have this problem @jaredculp ?  This is a very old issue and has artrofied over time.

I am not sure the code base is close enough any more.  But if you can reproduce this problem please let us known?

**Comment by jaredculp** [comment] 2021-08-02 13:14
@bbakerman looks like this issue was fixed in https://github.com/graphql-java/graphql-java/pull/2371. What does your release cadence look like?

**Comment by bbakerman** [comment] 2021-08-03 06:17
17.0 is imminent

**Closed** 2022-05-03 04:49 UTC
