### ISSUE TITLE
Using GraphQlContext to store query metadata

### ISSUE THREAD

**Issue by levans002** [graphql-java/graphql-java#860] opened 2017-12-08 20:31 UTC
Apologies if this question doesn't belong here.. I'm also using https://github.com/merapar/graphql-spring-boot-starter so this may end up there.

Imagine the schema:

```
type School {
    schoolId: String
    schoolName: String
    schoolAddress: Address
    classes: [Class]
}

type Class {
    classId: String
    className: String
    classRoomNumber: Int
    students: [Student]
}

type Student {
    studentId: String
    studentName: String
    grade: Int
}
```

Is there a way of getting `schoolId` from within the data fetcher for Student (without specifying it as a parameter)?

I see that I can set/get on: `dataFetchingEnvironment.dataGraphQLContext.subject.publicCredentials` to use it as a sort of fetching context to pass things to lower level fetchers.

The issue is this 'subject' is very security specific and I don't want to use it for general purpose key -> value data.

I assume I can create my own implementation of the `DataFetchingEnvironment` that returns a GraphQLContext wrapper or something, but I wanted to be sure:

1) This hasn't been done and I just cant find it
2) This context is per request and thread safe?

I'm assuming I'm missing something about why this is a horrible idea. If it exists for security specific metadata, I would think it would also exist for general data?

**Comment by bbakerman** [comment] 2017-12-09 03:10
> Is there a way of getting schoolId from within the data fetcher for Student (without specifying it as a parameter)?

No - arguments to fields are declared in the schema so a top level like

     type Query {
         school(schoolId : ID) : School
     }

That top level query type has a school field and the data fetcher behind that gets the schoolId as an agument

Have a look in here at the section "DataFecthers" : http://graphql-java.readthedocs.io/en/v6/execution.html

The execution context is typically per request.  But I can say for sure since I havent used graphql-spring-boot

The execution context can be a place to put security tokens and so on that you need to get data in your fetchers

>  I assume I can create my own implementation of the DataFetchingEnvironment that returns a GraphQLContext wrapper or something, but I wanted to be sure:

Yes you can - see that link

**Comment by bbakerman** [comment] 2017-12-09 03:10
Closing this as its not a bug

**Closed by bbakerman** 2017-12-09 03:10 UTC
